Repository MichaIng/DietPi, pull requests merged in 2018-12, with the labels that each got.

#2314 Dev > Beta
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_114/nginx.sites-dietpi.nextcloud.config
  .conf/dps_31/99-dietpi-kodi.rules
  .conf/dps_47/apache.owncloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_48/lighttpd.pydio.conf
  .conf/dps_48/nginx.pydio.conf
  .conf/dps_48/nginx.sites-dietpi.pydio.config
  .conf/dps_6/50-dietpi-rk3399.rules
  .conf/dps_6/xorg_rk3399.conf
  .conf/dps_6/xorg_xu4.conf
  .conf/dps_83/apache2.conf
  .conf/dps_85/nginx.conf
  .conf/dps_85/nginx.default
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/login
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/udev/rules.d/10-wifi-disable-powermanagement.rules
Labels: Beta

#2316 Dev > Beta
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/server_version-6
Labels: Beta

#2317 Dev > Beta
  .conf/desktop/apps/es2_gears.desktop
  .conf/desktop/apps/es2_info.desktop
  .conf/desktop/apps/glx_gears.desktop
  .conf/desktop/apps/glx_info.desktop
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/server_version-6
Labels: Beta

#2326 DietPi-Patch | Critical Nginx patch to apply new sites-dietpi file naming
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Bug :beetle:

#2327 #2326 port to dev
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:

#2330 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/.version
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2324 DietPi-Software | Blynk: Preserve config file on reinstall, patch new dir structure
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:

#2338 DietPi-Software | Netdata: Fix critical bug that lead to netdata uninstall removing parts of the whole root directory, destroying the system
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Bug :beetle:, Priority High :high_brightness:

#2349 DietPi-Config | Coding
  dietpi/dietpi-config
  dietpi/func/dietpi-set_software
Labels: Enhancement :dash:

#2343 DietPi-Autostart | Minor enhancements
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/.dietpi-autostart_index
  dietpi/dietpi-autostart
  dietpi/dietpi-survey
  dietpi/login
  dietpi/patch_file
Labels: Enhancement :dash:

#2333 DietPi-Software | Nextcloud Talk: Minor install fix/enhancement and disable logging
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2335 DietPi-Drive_Manager | Add fsck on reboot for RootFS & more
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Enhancement :dash:, Feature Request :factory:

#2355 Make spelling consistent in file
  dietpi/dietpi-software
Labels: Visual

#2337 DietPi-Software | Netdata: Fix uninstall removing root dir and use netdata user
  .conf/dps_65/netdata.service
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:, Priority High :high_brightness:, Testing/testers required :arrow_down_small:

#2357 DietPi systemd order | Resolve some systemd unit order quirks
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/patch_file
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-kill_ssh.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
  rootfs/etc/systemd/system/kill-ssh-user-sessions-before-network.service
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
  rootfs/var/lib/dietpi/services/kill-ssh-user-sessions-before-network.sh
Labels: Bug :beetle:, Enhancement :dash:

#2361 DietPi-Software | ownCloud/Nextcloud: Config updates
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_47/apache.owncloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_85/nginx.conf
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:, Security

#2366 DietPi-Sync | Resolve rsync option string bug
  CHANGELOG.txt
  dietpi/dietpi-sync
  dietpi/patch_file
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/cron.hourly/dietpi
Labels: Bug :beetle:, Enhancement :dash:

#2373 META | Add FeatHub page to README.md
  README.md
Labels: Information :information_source:, META

#2369 DietPi-Software | Add Medusa as replacement for SickRage
  CHANGELOG.txt
  README.md
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Software Request :cd:
