Repository MichaIng/DietPi, pull requests merged in 2018-04, with the labels that each got.

#1671 DietPi-Boot | Various enhencements
  CHANGELOG.txt
  dietpi/boot
  dietpi/patch_file
Labels: enhancement :dash:

#1685 Added new devices to selection list in PREP-Script
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: enhancement :dash:

#1684 Added LeMaker Guitar as device
  dietpi/dietpi-obtain_hw_model
Labels: enhancement :dash:

#1686 DietPi-Backup/Sync | Add free space check before run
  dietpi/dietpi-backup
Labels: enhancement :dash:

#1694 Coding | Replace remaining "clear" commands with "printf '\ec'"
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: enhancement :dash:

#1699 DietPi-PREP | Fine tuning
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-banner
Labels: enhancement :dash:

#1700 DietPi-Software | Some locale handling improvements, based issue I faced
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Bug :beetle:, enhancement :dash:

#1708 v6.7
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  boot_xu4.ini
  dietpi/.version
  dietpi/conf/smb.conf
  dietpi/dietpi-backup
  dietpi/dietpi-banner
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-obtain_hw_model
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_smbclient
  dietpi/func/dietpi-set_software
  dietpi/login
  dietpi/patch_file
  dietpi/server_version-6
Labels: enhancement :dash:

#1705 Update PREP_SYSTEM_FOR_DIETPI.sh
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: enhancement :dash:

#1704 Update dietpi-obtain_hw_model
  dietpi/dietpi-obtain_hw_model
Labels: enhancement :dash:

#1714 DietPi-Software | Pi-hole: Enable support for FTLDNS
  CHANGELOG.txt
  dietpi/dietpi-logclear
  dietpi/dietpi-services
  dietpi/patch_file
Labels: enhancement :dash:

#1713 DietPi-Drive_Manager | Added ability to adjust reserved blocks percentage on ext4 file system
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Feature Request :factory:, enhancement :dash:

#1723 DietPi-Software | Gitea 1.3.2 -> 1.4.0
  dietpi/dietpi-software
Labels: enhancement :dash:

#1728 DietPi-Software | Minor code improvements
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Testing/testers required :arrow_down_small:, enhancement :dash:

#1731 DietPi-Software + Globals | ownCloud/Nextcloud + G_CONFIG_INJECT: Further code and visual improvements
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: enhancement :dash:
