Repository MichaIng/DietPi, pull requests merged in 2018-11, with the labels that each got.

#2208 DietPi-Software | Code enhancements
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:

#2222 Dev > Beta
  CHANGELOG.txt
  dietpi/conf/roonbridge.service
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/cron.hourly/dietpi
  rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta

#2214 DietPi-Software | Reinstalls: Better handle existing configs and install dirs
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/create_mysql_db
Labels: Bug :beetle:, Enhancement :dash:

#2224 DietPi-Software | OpenBazaar: Pre-configure to allow client connection
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2227 DietPi-Globals | G_CONFIG_INJECT: Auto escaping of special characters
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
Labels: Enhancement :dash:

#2230 Dev > Beta
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/.version
  dietpi/boot
  dietpi/conf/apache.ownnextcloud.conf
  dietpi/conf/lighttpd.nextcloud.conf
  dietpi/conf/nginx.sites-dietpi.nextcloud.config
  dietpi/conf/nginx.sites-dietpi.owncloud.config
  dietpi/dietpi-software
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-optimal_mtu
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta

#2232 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2234 Dev > Beta
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta

#2235 Dev > Beta
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2236 Dev > Beta
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
Labels: Beta

#2248 DietPi-Globals | Possible fixes for getcwd error
  dietpi/func/dietpi-globals
Labels: Bug :beetle:, Enhancement :dash:

#2247 DietPi-Software | Docker: Set docker data via config file instead of systemd unit
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#2253 Dev > Beta
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-cleaner
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
Labels: Beta

#2255 Dev > Beta
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2258 Dev > Beta
  CHANGELOG.txt
  dietpi/boot
  dietpi/dietpi-software
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-set_software
  dietpi/login
  dietpi/server_version-6
Labels: Beta

#2259 v6.18
  CHANGELOG.txt
  dietpi/conf/apache.pydio.conf
  dietpi/conf/lighttpd.pydio.conf
  dietpi/conf/nginx.sites-dietpi.pydio.config
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2262 Tiny spelling fix
  BRANCH_SYSTEM.md
Labels: Enhancement :dash:, META

#2265 DietPi-Set_Hardware | Detect changed LCD control files on Odroid C1/2
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Bug :beetle:, Odroid C1, Odroid C2

#2272 Add Cloudflare DNS config option
  dietpi/dietpi-config
Labels: Enhancement :dash:

#2276 Dev > Beta
  .github/PULL_REQUEST_TEMPLATE.md
  .meta/dietpi-fan_control
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/conf/apache.pydio.conf
  dietpi/conf/lighttpd.pydio.conf
  dietpi/conf/nginx.sites-dietpi.pydio.config
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  dietpi/preboot
  dietpi/server_version-6
Labels: Beta

#2280 Dev > Beta
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/server_version-6
Labels: Beta

#2277 DietPi-Software | Single missing white space and many minor code improvements
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2274 DietPi-Software | Tautulli: Fix (re)install
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Bug :beetle:

#2292 Dev > Beta
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/server_version-6
Labels: Beta

#2281 Beta > Release
  .github/PULL_REQUEST_TEMPLATE.md
  .meta/dietpi-fan_control
  .meta/dietpi-survey_report
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/conf/apache.ownnextcloud.conf
  dietpi/conf/apache.pydio.conf
  dietpi/conf/lighttpd.nextcloud.conf
  dietpi/conf/lighttpd.pydio.conf
  dietpi/conf/nginx.sites-dietpi.nextcloud.config
  dietpi/conf/nginx.sites-dietpi.owncloud.config
  dietpi/conf/nginx.sites-dietpi.pydio.config
  dietpi/conf/roonbridge.service
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-optimal_mtu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  dietpi/func/obtain_network_details
  dietpi/login
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/cron.hourly/dietpi
  rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Enhancement :dash:

#2287 Updated Blynk Server Install
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2303 Dev > Beta
  .gitattributes
  .meta/conf/desktop/apps/dietpi-backup.desktop
  .meta/conf/desktop/apps/dietpi-bugreport.desktop
  .meta/conf/desktop/apps/dietpi-cleaner.desktop
  .meta/conf/desktop/apps/dietpi-config.desktop
  .meta/conf/desktop/apps/dietpi-cron.desktop
  .meta/conf/desktop/apps/dietpi-drive_manager.desktop
  .meta/conf/desktop/apps/dietpi-justboom.desktop
  .meta/conf/desktop/apps/dietpi-launcher.desktop
  .meta/conf/desktop/apps/dietpi-process_tool.desktop
  .meta/conf/desktop/apps/dietpi-software.desktop
  .meta/conf/desktop/apps/dietpi-sync.desktop
  .meta/conf/desktop/apps/dietpi-update.desktop
  .meta/conf/desktop/apps/kodi.desktop
  .meta/conf/desktop/apps/opentyrian.desktop
  .meta/conf/desktop/gtk/.gtk-bookmarks
  .meta/conf/desktop/icons/dietpi-icon.png
  .meta/conf/desktop/icons/grey_16x16.png
  .meta/conf/desktop/icons/justboom.png
  .meta/conf/desktop/icons/kodi-icon.png
  .meta/conf/desktop/lxde/lxde-rc.xml
  .meta/conf/desktop/lxde/panel
  .meta/conf/desktop/lxde/pcmanfm-desktopitems.conf
  .meta/conf/desktop/lxde/pcmanfm.conf
  .meta/conf/desktop/wallpapers/dietpi-logo_1080p.png
  .meta/conf/desktop/wallpapers/dietpi-logo_inverted_1080p.png
  .meta/dietpi-survey_report
  .meta/images/76mm_rounder_sticker.bmp
  .meta/images/76mm_rounder_sticker.png
  .meta/images/dietpi-logo.png
  .meta/images/dietpi-logo_150.png
  .meta/images/dietpi-logo_256.png
  .meta/images/dietpi-logo_80.png
  .meta/images/dietpi-logo_boot.bmp
  .meta/images/dietpi-logo_inverted.png
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/.version
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/login
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta
