Repository MichaIng/DietPi, pull requests merged in 2018-06, with the labels that each got.

#1819 DietPi-RAMdisk/log | Systemd want's absolute command paths
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
Labels: Bug :beetle:, Debian Buster

#1825 General | Adjust and unify password handling to increase security
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Via Forum, enhancement :dash:

#1822 [WIP] DietPi-Bugreport/Survey | Rework
  dietpi/dietpi-bugreport
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/dietpi-globals
  dietpi/patch_file
Labels: Priority High :high_brightness:, enhancement :dash:

#1820 GitHub | Update issue templates, separate between bug report and feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: META, Priority Low :low_brightness:

#1834 DietPi-Survey | Tuning
  dietpi/dietpi-survey
  dietpi/dietpi-update
Labels: enhancement :dash:

#1830 DietPi-PREP | Several
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: enhancement :dash:

#1839 Generel | Remove "net-tools" commands in favour of "ip" and "/proc/" + "/sys/" scraping
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/boot
  dietpi/dietpi-bugreport
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
Labels: enhancement :dash:

#1847 META | Add GPLv2 license text to repo root
  LICENSE
Labels: META

#1853 DietPi-Obtain_network_details | Prefer and use only active network devices to estimate IP
  dietpi/dietpi-cloudshell
  dietpi/func/obtain_network_details
Labels: Bug :beetle:, enhancement :dash:

#1848 META | Separate contribution guidelines + software/device request templates
  .github/ISSUE_TEMPLATE/image_request.md
  .github/ISSUE_TEMPLATE/software_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: META

#1859 RPi | Disable "initial_turbo" setting within config.txt
  CHANGELOG.txt
  config.txt
  dietpi/patch_file
Labels: Bug :beetle:, RPi

#1863 RPi | Remove "config.txt" from non-RPi devices
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  config.txt
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: enhancement :dash:

#1865 DietPi-Software | Add Roon Extension Manager
  dietpi/dietpi-software
Labels: Software Request :cd:

#1867 DietPi-Globals | Speed up G_DIETPI-NOTIFY, let PS1 promt kill processing animation as last resort
  dietpi/dietpi-process_tool
  dietpi/func/dietpi-globals
  rootfs/etc/bashrc.d/dietpi-ps1_kill_animation.sh
Labels: enhancement :dash:

#1872 DietPi-Software | Uninstall, minor general code and visual improvements
  dietpi/dietpi-software
Labels: enhancement :dash:
