Repository MichaIng/DietPi, pull requests merged in 2018-02, with the labels that each got.

#1497 Update dietpi-set_hardware
  dietpi/func/dietpi-set_hardware
Labels: enhancement

#1475 DietPi-Software | MariaDB: Prepare database directory before installation
  dietpi/dietpi-software
Labels: enhancement

#1509 General | v6.2 polishing
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: bug, enhancement

#1521 DietPi-Software | CertBot: Also Minio challenge needs to be patched, as we actively preferred 'tls-sni' here.
  dietpi/patch_file
Labels: bug

#1532 v6.2
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/conf/nginx.site-available-default
  dietpi/conf/nginx.sites-dietpi.nextcloud.config
  dietpi/conf/nginx.sites-dietpi.owncloud.config
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-banner
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpu_set
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-logclear
  dietpi/dietpi-morsecode
  dietpi/dietpi-obtain_hw_model
  dietpi/dietpi-process_tool
  dietpi/dietpi-ramdisk
  dietpi/dietpi-ramlog
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/change_hostname
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-optimal_mtu
  dietpi/func/dietpi-set_core_environment
  dietpi/func/dietpi-set_curlftpfs
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_nfsclient
  dietpi/func/dietpi-set_smbclient
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/func/obtain_network_details
  dietpi/func/run_ntpd
  dietpi/login
  dietpi/misc/dietpi-justboom
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/server_version-6
Labels: enhancement

#1522 DietPi-Software | Minio: Installation and CertBot enhancements + new globals function
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: enhancement

#1507 DietPi | Switch from rc.local to dietpi-postboot.service
  CHANGELOG.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-software
  dietpi/func/dietpi-set_core_environment
  dietpi/login
  dietpi/patch_file
  dietpi/postboot
Labels: Priority Low, enhancement

#1525 DietPi-Software | ownCloud/Nextcloud: Fix potential issue with wrong data directory entries, if backups are migrated to different server
  dietpi/dietpi-software
Labels: enhancement

#1424 DietPi-Globals | G_RUN_CMD: Alternative output string
  dietpi/func/dietpi-globals
Labels: Priority Low, enhancement

#1547 Added configuration for WPA2 Enterprise
  dietpi.txt
  dietpi/func/dietpi-set_hardware
Labels: enhancement

#1553 DietPi-LetsEncrypt | Lighttpd: Renewal fix and HSTS support + cleanup
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: bug, enhancement

#1562 DietPi-Software | PHP: Buster support for Lighttpd + Nginx
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Debian Buster, enhancement
