Repository MichaIng/DietPi, pull requests merged in 2018-09, with the labels that each got.

#2049 DietPi-Login | Workaround in case of unsupported SSH client terminal
  rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
Labels: External Bug :beetle:

#2068 v6.15
  .meta/survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/login
  dietpi/patch_file
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/network/if-up.d/dietpi-disable_offload
  rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: enhancement :dash:

#2076 General | Fix "wireless-tools" pre-up script bug
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/patch_file
Labels: External Bug :beetle:

#2077 Revamp the README
  README.md
Labels: META, enhancement :dash:

#2080 v6.16
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/.version
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/postboot
  dietpi/server_version-6
Labels: enhancement :dash:

#2065 DietPi-Software | ownCloud/Nextcloud: Install update for NC14 + .well-known redirect
  CHANGELOG.txt
  dietpi/conf/apache.ownnextcloud.conf
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Bug :beetle:, Debian Jessie, Feature Request :factory:, enhancement :dash:

#2097 DietPi-Update | Check GitHub repo first
  dietpi/dietpi-update
Labels: enhancement :dash:
