Repository MichaIng/DietPi, pull requests merged in 2018-08, with the labels that each got.

#1988 Coding | Replace "dpkg --get-selections | grep X" with "dpkg-query -s X"
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-launcher
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
Labels: enhancement :dash:

#1976 General | Mask systemd-logind by default, allow to unmask via dietpi.txt and libpam-systemd install
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: enhancement :dash:

#1993 DietPi-Software | Renaming MariaDB webserver stacks to have well-known "LAMP" stack again.
  dietpi/dietpi-software
Labels: META

#1992 DietPi-Software | Add folding@home to software list
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#1994 DietPi-Drive_Manager | Add NFSv3 handling
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-drive_manager
  dietpi/func/dietpi-globals
  dietpi/patch_file
Labels: Feature Request :factory:, enhancement :dash:

#1998 DietPi-Globals | G_INIT(): Check for concurrent DietPi script executions
  dietpi/func/dietpi-globals
Labels: Bug :beetle:, enhancement :dash:

#2000 DietPi-Set_userdata | Remove possible DietPi script loops + other improvements
  dietpi/dietpi-drive_manager
  dietpi/func/dietpi-set_userdata
Labels: Bug :beetle:, enhancement :dash:

#2003 DietPi-Software | Pi-hole: Implement/test version 4
  dietpi/dietpi-software
Labels: enhancement :dash:

#2002 DietPi-LetsEncrypt | Add user information about HTTPS and HSTS
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: enhancement :dash:

#2005 DietPi-Software | Enable RPi unrar support for Jessie and Buster
  dietpi/dietpi-software
Labels: Debian Buster, Debian Jessie, RPi, enhancement :dash:

#2009 DietPi-Globals | G_INIT(): Hide debug output
  dietpi/func/dietpi-globals
Labels: enhancement :dash:

#2011 v6.13
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/conf/smb.conf
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-ramdisk
  dietpi/func/dietpi-ramlog
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/func/run_ntpd
  dietpi/login
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/postboot
  dietpi/server_version-6
  rootfs/etc/cron.hourly/dietpi
  rootfs/etc/cron.minutely/readme.txt
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
  rootfs/var/lib/dietpi/services/kill-ssh-user-sessions-before-network.sh
Labels: enhancement :dash:

#2029 v6.14
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/conf/brutefir.service
  dietpi/conf/brutefir_config
  dietpi/conf/nginx.sites-dietpi.nextcloud.config
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-morsecode
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/obtain_network_details
  dietpi/func/run_ntpd
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: enhancement :dash:

#2040 DietPi-Software | phpMyAdmin: New workaround for Lighttpd + phpMyAdmin APT issue
  dietpi/dietpi-software
Labels: External Bug :beetle:

#2042 DietPi-Globals | Minor enhancements and G_CONFIG_INJECT additions
  dietpi/func/dietpi-globals
Labels: enhancement :dash:
