Repository MichaIng/DietPi, pull requests merged in 2018-10, with the labels that each got.

#2111 META | DietPi-Survey_report: Coding optimization
  .meta/dietpi-survey_report
  dietpi/dietpi-survey
Labels: Enhancement :dash:, META

#2119 DietPi-Process_tool | Fix loop + other coding improvements
  dietpi/dietpi-process_tool
Labels: Bug :beetle:, Enhancement :dash:

#2125 DietPi-(Pre-)Boot | Rework network init workarounds
  dietpi/boot
  dietpi/func/dietpi-wifidb
  dietpi/func/obtain_network_details
  dietpi/preboot
Labels: Bug :beetle:, Enhancement :dash:

#2136 DietPi-Globals | G_WHIP speed-up, hopefully 😄
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:

#2137 DietPi-Update | Separate current and target branch info
  dietpi/func/dietpi-globals
Labels: Bug :beetle:

#2141 DietPi-Survey | Add Git user/branch to survey upload file
  .meta/dietpi-survey_report
  dietpi/dietpi-survey
Labels: META

#2145 DietPi-Patch | Autorun 2nd pre-v6.17 update
  dietpi/patch_file
Labels: Beta, Enhancement :dash:

#2146 DietPi-Globals | Allow to override $WHIP_SIZE_* values
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
Labels: Beta, Visual

#2148 DietPi-PREP | Fix missing G_DISTRO* + G_HW_MODEL for "dietpi-set_software apt-mirror"
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Bug :beetle:, Enhancement :dash:

#2150 Dev > Beta
  .meta/dietpi-survey_report
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/.version
  dietpi/boot
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-morsecode
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/change_hostname
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-optimal_mtu
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/func/dietpi-wifidb
  dietpi/func/obtain_network_details
  dietpi/func/run_ntpd
  dietpi/login
  dietpi/misc/dietpi-justboom
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/preboot
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta

#2152 Dev > Beta
  .meta/dietpi-survey_report
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/server_version-6
Labels: Beta

#2166 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi.txt
  dietpi/conf/mpd.conf
  dietpi/dietpi-autostart
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2167 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/server_version-6
Labels: Beta

#2174 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/server_version-6
Labels: Beta

#2175 Dev > Beta
  CHANGELOG.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/server_version-6
Labels: Beta

#2176 Dev > Beta
  CHANGELOG.txt
  dietpi/server_version-6
Labels: Beta

#2178 Dev > Beta
  CHANGELOG.txt
Labels: Beta

#2179 Dev > Beta
  CHANGELOG.txt
Labels: Beta

#2186 DietPi-Software | Nextcloud: Fix failed install due to "config.sample.php"
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Bug :beetle:

#2188 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/boot
  dietpi/dietpi-config
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2195 Dev > Beta
  CHANGELOG.txt
  dietpi/func/dietpi-globals
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta

#2194 DietPi-Update | Do not show RC version on subversion update
  CHANGELOG.txt
  dietpi/dietpi-update
Labels: Visual

#2191 DietPi-Obtain_network_details | "chmod /DietPi/dietpi/.network" only as root user, to prevent "not permitted" error
  CHANGELOG.txt
  dietpi/func/obtain_network_details
Labels: Visual

#2197 DietPi-Software | Nextcloud Talk with configured TURN server now available for install
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#2201 DietPi-Software | Pi-hole: Allow user choice whether to show blocking page
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Feature Request :factory:

#2193 DietPi-WiFiDB | Enhancements
  dietpi/func/dietpi-wifidb
Labels: Enhancement :dash:

#2204 Dev > Beta
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-wifidb
  dietpi/func/obtain_network_details
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta
