Repository MichaIng/DietPi, pull requests merged in 2018-03, with the labels that each got.

#1571 DietPi-Software | FFmpeg: Fix backports dependency issues for all Odroids
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/patch_file
Labels: Investigation Required, Odroids/Meveric, bug

#1583 DietPi-Software | Minor quoting and coding enhancements
  dietpi/dietpi-software
Labels: Priority Low, enhancement

#1596 DietPi-Prep | Move microcode installation from DietPi-Prep to FirstRun
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/patch_file
Labels: enhancement

#1597 DietPi-Prep | Force purging of dhcpcd5, as this will not be autoremoved in all cases
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/patch_file
Labels: enhancement

#1578 Includes option for minutely cronjobs
  dietpi/dietpi-cron
Labels: enhancement

#1611 DietPi-dphys-swapfile | Remove entry from fstab when disabling + reorder/cleanup
  dietpi/func/dietpi-set_dphys-swapfile
Labels: enhancement

#1616 DietPi-Process_Tool | Add ability to read custom processes from include file
  CHANGELOG.txt
  dietpi/dietpi-process_tool
Labels: enhancement

#1618 DietPi-Config | Allow changing display resolution for VMs by adjusting GRUB GFX values
  CHANGELOG.txt
  dietpi/dietpi-config
Labels: VM_x64, enhancement

#1624 DietPi-Update | Added option to rerun the current subversion patch: "dietpi-update -1"
  dietpi/dietpi-update
  dietpi/patch_file
Labels: enhancement

#1629 General | Replace "clear" with "printf '\ec'"
  CHANGELOG.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-banner
  dietpi/dietpi-bugreport
  dietpi/dietpi-config
  dietpi/dietpi-cron
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-morsecode
  dietpi/dietpi-process_tool
  dietpi/dietpi-sync
  dietpi/func/dietpi-set_curlftpfs
  dietpi/func/dietpi-set_nfsclient
  dietpi/func/dietpi-set_smbclient
Labels: Testing/testers required, enhancement

#1635 DietPi-Environment | Some service-, config- and code adjustments
  dietpi/func/dietpi-set_core_environment
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: enhancement

#1586 DietPi-Software | Allow uninstall order by switching to method of install loop
  dietpi/dietpi-software
Labels: enhancement

#1649 DietPi-Software | MPD: Resolved an issue where "libwrap0" (libwrap.so.0) was missing to start MPD service
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, enhancement :dash:

#1650 DietPi-Services | Start/Stop order is now based on service dependencies
  CHANGELOG.txt
  dietpi/dietpi-services
Labels: enhancement :dash:

#1661 DietPi-Run_ntpd | Buster: Adjusted timedatectl status check, as output changed with latest systemd update
  dietpi/func/run_ntpd
Labels: Bug :beetle:, Debian Buster, Priority Low :low_brightness:

#1665 DietPi-Prep | Remove minutely running "make_nas_processes_faster" cron job
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/patch_file
Labels: enhancement :dash:
