Repository MichaIng/DietPi, pull requests merged in 2018-05, with the labels that each got.

#1738 DietPi-LetsEncrypt | Error handling + further rework
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
  dietpi/func/dietpi-globals
Labels: Bug :beetle:, Via Forum, enhancement :dash:

#1745 DietPi-PREP | Fix DietPi-RAMdisk issue
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Bug :beetle:, PREP

#1746 DietPi-Globals | G_CONFIG_INJECT: Final fixes
  dietpi/func/dietpi-globals
Labels: Bug :beetle:, Question :grey_question:

#1761 DietPi-Drive_Manager | Improved method of reading available dev drives
  dietpi/dietpi-drive_manager
Labels: enhancement :dash:

#1763 DietPi-Drive_Manager | Check & Repair
  dietpi/dietpi-drive_manager
Labels: Feature Request :factory:, enhancement :dash:

#1774 DietPi-Software | Non-APT software updates
  dietpi/dietpi-software
Labels: Testing/testers required :arrow_down_small:, enhancement :dash:

#1779 Update dietpi-set_hardware
  dietpi/func/dietpi-set_hardware
Labels: SparkySBC

#1786 DietPi-PREP | Never tired of working on this
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: enhancement :dash:

#1789 DietPi-Software | Koel: Workaround due to Node 10 incompatibility
  dietpi/dietpi-software
Labels: External Bug :beetle:

#1628 General | Switch from NTP to systemd-timesyncd
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/boot
  dietpi/conf/cron.daily_dietpi
  dietpi/conf/cron.hourly_dietpi
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/func/run_ntpd
  dietpi/patch_file
Labels: Priority Low :low_brightness:, enhancement :dash:

#1790 DietPi-Login | Completely remove sudo/root requirements
  dietpi/func/obtain_network_details
  dietpi/login
  dietpi/patch_file
Labels: enhancement :dash:

#1798 DietPi-Login | Move DietPi-Globals and login scripts into new /etc/bashrc.d/ global custom interactive shell script directory
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-bugreport
  dietpi/func/dietpi-set_core_environment
  dietpi/patch_file
Labels: enhancement :dash:

#1802 RootFS folder structure on github for easier system file updates
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-update
  dietpi/func/dietpi-set_core_environment
  dietpi/patch_file
  rootfs/etc/bashrc.d/dietpi-login.sh
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/cron.hourly/dietpi
  rootfs/etc/sysctl.d/dietpi.conf
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/etc/systemd/system/kill-ssh-user-sessions-before-network.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
  rootfs/var/lib/dietpi/services/kill-ssh-user-sessions-before-network.sh
Labels: PREP, enhancement :dash:
