Repository MichaIng/DietPi, pull requests merged in 2019-02, with the labels that each got.

#2506 DietPi-PREP | Fix wrong chmod
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Bug :beetle:, PREP

#2490 DietPi-Software | MariaDB: v10.3 update on Buster requires settings patch
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/pre-patch_file
Labels: Bug :beetle:, Debian Buster

#2509 DietPi-Update | Fix v6.20 update issues
  CHANGELOG.txt
  dietpi/dietpi-update
  dietpi/patch_file
Labels: Bug :beetle:, Priority High :high_brightness:

#2527 dietpi-autostart comment typo
  dietpi/dietpi-autostart
Labels: Enhancement :dash:

#2528 PREP_SYSTEM_FOR_DIETPI.sh comment typo fixes
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Visual

#2538 DietPi-Software | Aria2: Config tweak/fix
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2539 DietPi-Software | Java: Reapply workaround to fix ARM install issue
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: External Bug :beetle:

#2526 DietPi-Software | WireGuard fixes + OpenVPN/WiFi Hotspot enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2541 DietPi-Login | Failsafe hardening and resolving possible first run loops
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/login
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-postboot.service
Labels: Enhancement :dash:

#2552 DietPi-Software | Remot3.it: Fix install due to changed GitHub repo
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: External Bug :beetle:

#2544 DietPi-Login | Fix and tuning
  dietpi/dietpi-login
  rootfs/etc/bashrc.d/dietpi-login.sh
Labels: Bug :beetle:, Enhancement :dash:

#2525 DietPi-Software | Emby-server: Install latest version via "api.github.com"
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2562 DietPi-Software | Koel/MineOS: Fix install on ARMv8 systems
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: External Bug :beetle:

#2559 General | Remove dependency on p7zip-full, use lightweight p7zip/7zr instead
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-bugreport
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Enhancement :dash:

#2555 General | Remove /DietPi/dietpi/.version from GitHub repo
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/.version
  dietpi/dietpi-update
Labels: Enhancement :dash:

#2563 Update to get correct CPU temp
  dietpi/func/dietpi-globals
Labels: Bug :beetle:

#2565 DietPi-Start_kodi | Do not load DietPi-Globals, since G_HW_MODEL is required only
  dietpi/misc/start_kodi
Labels: Enhancement :dash:

#2550 DietPi-Set_Hardware | I-Sabre-K2M: Fix module source build, add informational comments
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Bug :beetle:, RPi, Testing/testers required :arrow_down_small:

#2570 DietPi-Software | Pi-hole: Fix "pihole -up"
  CHANGELOG.txt
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Bug :beetle:

#2574 DietPi-Obtain_network_details | Skip loading DietPi-Globals
  dietpi/func/obtain_network_details
Labels: Coding, Enhancement :dash:

#2580 DietPi-Software | GMediaRender: Service starts with obtained IP
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2578 DietPi-Software | UrBackup: Update install links to v2.3.7
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2582 DietPi-Software | GMediaRender: Enable Buster support by using the up-to-date APT repo package
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Debian Buster, Enhancement :dash:

#2571 DietPi-Software | WireGuard: Harden "sid" repo handling on RPi
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:, RPi

#2572 DietPi-Globals | G_AG*: Remove potentially harmful force options + other enhancements
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:

#2586 DietPi | Fix wrong shown connection state if IP+route is active but link "DOWN"
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/obtain_network_details
Labels: Bug :beetle:, Visual

#2594 DietPi-Software | Deluge: Fix deluge-console access and several other enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:
