Repository MichaIng/DietPi, pull requests merged in 2019-01, with the labels that each got.

#2376 DietPi-Software | OpenSSH: Host key regeneration quirks
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/preboot
  rootfs/etc/systemd/system/dietpi-preboot.service
Labels: Bug :beetle:, Security

#2385 DietPi-Software | Mopidy: Installer update
  .conf/dps_118/mopidy.conf
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Bug :beetle:, Enhancement :dash:

#2381 DietPi-Software | MPD: Update installer
  CHANGELOG.txt
  dietpi/conf/mpd.conf
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Enhancement :dash:

#2393 General | Clean and remove /DietPi/dietpi/conf
  .conf/dps_128/mpd.conf
  .conf/dps_51/run
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/conf/network_interfaces
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  rootfs/var/lib/dietpi/dietpi-software/conf/cava.conf
Labels: Enhancement :dash:

#2397 DietPi-Software | Samba: Move disk cache to RAM
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2402 DietPi-Config | RPi: Enhance and replace some obsolete dietpi.txt settings
  CHANGELOG.txt
  config.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/preboot
Labels: Enhancement :dash:

#2398 DietPi-Software | WireGuard: Now available for install
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Software Request :cd:, Testing/testers required :arrow_down_small:

#2405 RPi | Outsource headless mode to DietPi-Set_Hardware + minor enhancements
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/preboot
Labels: Enhancement :dash:, RPi

#2410 DietPi-Software | Airsonic: Update installer to latest version
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2421 Coding | Replace "which" command with builtin "command -v"
  dietpi/dietpi-autostart
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/preboot
  rootfs/etc/network/if-up.d/dietpi-disable_offload
Labels: Enhancement :dash:

#2424 Coding | Replace "awk" by "mawk"
  .meta/dietpi-cloud-migration
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-sync
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/misc/dietpi-justboom
  dietpi/postboot
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Enhancement :dash:

#2420 DietPi-Software | WireGuard: Install fine tuning
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2432 Beta v6.20.1 => v6.20.2
  .conf/desktop/lxde/panel
  .meta/dietpi-cloud-migration
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  config.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-launcher
  dietpi/dietpi-morsecode
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/login
  dietpi/misc/dietpi-justboom
  dietpi/misc/dietpi-nordvpn
  dietpi/patch_file
  dietpi/postboot
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/network/if-up.d/dietpi-disable_offload
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta

#2437 DietPi-Config/Set_Hardware | Headless mode fine tuning and coding
  config.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/preboot
Labels: Enhancement :dash:

#2441 DietPi-Software | PHP: Fix PHP package naming due to Debian repo changes in Stretch
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Debian Stretch, External Bug :beetle:

#2448 DietPi-Software | Gitea 1.4 -> 1.7
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2450 DietPi-Software | Grafana: Switch to official APT repo witch all archs
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:, Testing/testers required :arrow_down_small:
