Repository MichaIng/DietPi, pull requests merged in 2019-05, with the labels that each got.

#2753 DietPi-Software | Java: On Jessie, download our self-hosted packages
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: External Bug :beetle:

#2756 Feature/automated build
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Enhancement :dash:, PREP

#2767 DietPi-PREP | Trivial text edit for better clarity
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Visual

#2768 DietPi-Software | SABnzbd: Several minor install updates
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Enhancement :dash:

#2770 Beta v6.23.1
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  boot_c1.ini
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2771 Beta v6.23.1 > Jessie-support
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  boot_c1.ini
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2773 DietPi-Software | Jackett: Use new (v0.11) standalone version on non-ARMv6 devices
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2779 DietPi-Software | Blynk Server: Fix logging issue and enable Buster support
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Bug :beetle:, Debian Buster, Enhancement :dash:

#2774 Beta v6.23.2
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  CHANGELOG.txt
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-explorer
  dietpi/dietpi-morsecode
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2785 Beta v6.23.2 > Jessie-support
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  CHANGELOG.txt
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-explorer
  dietpi/dietpi-morsecode
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2788 Beta v6.23.3
  CHANGELOG.txt
  dietpi/dietpi-cleaner
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2799 DietPi-Software | PHP: Install via Raspbian Buster repo on ARMv6
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: ARMv6, Bug :beetle:, RPi

#2800 Beta v6.24
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta

#2809 DietPi-Software | Fix for certain issues related with PHP7.3 (on ARMv6)
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Bug :beetle:

#2818 Beta v6.24.1
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta

#2786 DietPi-Services 2.0
  .conf/desktop/apps/dietpi-process_tool.desktop
  .conf/desktop/apps/dietpi-services.desktop
  CHANGELOG.txt
  README.md
  dietpi/dietpi-launcher
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
Labels: Enhancement :dash:

#2845 DietPi-Services 2.0 | Fine tuning part one
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/func/dietpi-globals
Labels: Coding :bookmark_tabs:

#2853 DietPi-Services 2.0 | Fine tuning part 2
  dietpi/dietpi-services
Labels: Coding :bookmark_tabs:

#2866 DietPi-Services 2.0 | Fine tuning part 3
  dietpi/dietpi-services
Labels: Coding :bookmark_tabs:, Enhancement :dash:

#2875 DietPi-Software | FFmpeg: On RPi, install new package from archive.respberrypi.org
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:, RPi
