Repository MichaIng/DietPi, pull requests merged in 2019-03, with the labels that each got.

#2606 DietPi-Sync | Empty source check, dry run merge and minor fixes/enhancements
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-sync
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:, Feature Request :factory:

#2621 DietPi-Software | Netdata: Fall back to Debian stretch-backports APT package
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Enhancement :dash:

#2625 DietPi-Software | Store global password with enhanced security
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/pre-patch_file
Labels: Debian Buster, Security

#2626 DietPi-Survey | Cleanup: Remove survey version and sent count from upload file
  .meta/dietpi-survey_report
  dietpi/dietpi-survey
  dietpi/patch_file
Labels: Enhancement :dash:, META

#2611 Beta v6.22.0
  .conf/dps_128/mpd.conf
  .conf/dps_6/xorg_xu4.conf
  .conf/dps_65/netdata.service
  .conf/dps_85/nginx.conf
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/image_request.md
  .github/ISSUE_TEMPLATE/software_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .meta/dietpi-cloud-migration
  .meta/dietpi-fan_control
  .meta/dietpi-survey_report
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  CONTRIBUTING.md
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  TESTING-BRANCH.md
  config.txt
  dietpi.txt
  dietpi/.version
  dietpi/boot
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-ramdisk
  dietpi/func/dietpi-set_dphys-swapfile
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/obtain_network_details
  dietpi/func/run_ntpd
  dietpi/login
  dietpi/misc/dietpi-nordvpn
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/postboot
  dietpi/pre-patch_file
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi-login.sh
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/bashrc.d/dietpi-unsupported_terminal.sh
  rootfs/etc/network/if-up.d/dietpi-disable_offload
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
Labels: Beta

#2633 DietPi-Software | rTorrent: Fix for config file not being in use + now runs as user "rtorrent"
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:

#2635 RPi | Remove "framebuffer_depth" handling completely which defaults to 16 which works in every known case
  CHANGELOG.txt
  config.txt
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Enhancement :dash:, RPi

#2636 System | Merge interactive bash DietPi scripts into one
  CHANGELOG.txt
  dietpi/dietpi-login
  dietpi/patch_file
  rootfs/etc/bashrc.d/dietpi-login.sh
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/bashrc.d/dietpi-ps1_kill_animation.sh
  rootfs/etc/bashrc.d/dietpi-unsupported_terminal.sh
  rootfs/etc/bashrc.d/dietpi.bash
Labels: Enhancement :dash:

#2554 DietPi-Software | Plex Media Server: Switch to new official ARM binaries
  CHANGELOG.txt
  dietpi/dietpi-process_tool
  dietpi/dietpi-software
Labels: ARMbaby, Enhancement :dash:

#2639 DietPi-Software | Nextcloud: Add OCM/OCS provider redirects as this is checked and printed as warning on admin panel
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_85/nginx.default
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2640 Beta v6.22.1
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_85/nginx.default
  .meta/dietpi-survey_report
  CHANGELOG.txt
  config.txt
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-login
  dietpi/dietpi-process_tool
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-ramlog
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi-login.sh
  rootfs/etc/bashrc.d/dietpi-posix-set-locale.sh
  rootfs/etc/bashrc.d/dietpi-ps1_kill_animation.sh
  rootfs/etc/bashrc.d/dietpi-unsupported_terminal.sh
  rootfs/etc/bashrc.d/dietpi.bash
Labels: Beta

#2643 Beta v6.22.2
  .meta/myip.php
  CHANGELOG.txt
  README.md
  dietpi/boot
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/preboot
  dietpi/server_version-6
Labels: Beta

#2649 DietPi-Banner | Support for custom colour codes
  dietpi/func/dietpi-banner
Labels: Enhancement :dash:

#2648 Beta v6.22.3
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta

#2654 v6.22
  CHANGELOG.txt
Labels: META

#2675 v6.22
  PREP_SYSTEM_FOR_DIETPI.sh
Labels: Bug :beetle:, PREP
