Repository MichaIng/DietPi, pull requests merged in 2019-04, with the labels that each got.

#2684 DietPi-Patch | Restart_DietPi_Update() needs to finish BEFORE any reboot can be done
  dietpi/patch_file
Labels: Bug :beetle:

#2688 DietPi-LetsEncrypt | Authentication method updates
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Enhancement :dash:

#2699 General | In systemd services use faster "dash" as script exec + log forwarding wrapper
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
Labels: Coding

#2678 DietPi-Config | Serial/UART rework: Allow to toggle login console on single serial devices
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Enhancement :dash:, Feature Request :factory:

#2702 DietPi-Software | Update Subsonic binary to v6.1.5
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2706 DietPi-Software | Transmission: Add password with escaped double quotes to prevent service startup failures in case
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#2710 DietPi-Banner MOTD
  CHANGELOG.txt
  dietpi/func/dietpi-banner
  rootfs/etc/cron.daily/dietpi
Labels: Enhancement :dash:

#2698 DietPi-Arr_to_RAM | Add systemd service and further enhancements
  CHANGELOG.txt
  dietpi/func/dietpi-globals
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
Labels: Enhancement :dash:, Feature Request :factory:

#2700 DietPi-Software | WireGuard: IPv6 and auto-upgrade fixes
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
  dietpi/pre-patch_file
Labels: Bug :beetle:, Enhancement :dash:

#2716 DietPi-Config | Fine tune proxy settings
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/patch_file
Labels: Enhancement :dash:

#2705 DietPi-Software | Subsonic: Now runs as own user "subsonic" + failsafe FFmpeg transcoder creation
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2718 DietPi-Autostart | Enable systemd-logind with AmiBerry fastboot
  CHANGELOG.txt
  dietpi/dietpi-autostart
Labels: Bug :beetle:, Enhancement :dash:

#2722 DietPi-Software | Plex Media Server: Install from/migrate to new official APT repo
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2723 DietPi-Software | Tor Hotspot: Mark WiFi Hotspot during regular pre-req check
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#2727 DietPi-Software | Fail2Ban: Rework and fix wrong loglevel value on Stretch
  dietpi/dietpi-software
Labels: Bug :beetle:, Debian Stretch, Enhancement :dash:

#2728 System | Debian Jessie: Apply APT list changes according to dropped support by Debian
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/func/dietpi-set_software
  dietpi/pre-patch_file
Labels: Debian Jessie, External Bug :beetle:

#2729 DietPi-Drive_Manager | Preserve encryptfs and vboxsf (VirtualBox shared folder) fstab entries
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Feature Request :factory:

#2735 DietPi-Software | PHP: Install PHP7.3 on all distro version
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_85/nginx.conf
  .meta/dietpi-cloud-migration
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:, Feature Request :factory:

#2740 DietPi-Software | Nextcloud Talk: Do not apply TLS on coTURN
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
Labels: Bug :beetle:, Debian Buster, Enhancement :dash:

#2741 System | Make DietPi systemd unit dependencies most strict
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramdisk.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
Labels: Enhancement :dash:

#2742 General | Move Jessie systems to "jessie-support" branch
  CHANGELOG.txt
  dietpi/patch_file
  dietpi/pre-patch_file
Labels: Debian Jessie, Information :information_source:
