Repository MichaIng/DietPi, pull requests merged in 2019-06, with the labels that each got.

#2881 change gitea to 1.8 for stable purpose
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2883 DietPi-Software | myMPD: Install latest master + fixes
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#2833 DietPi-PreBoot | Separate first boot and regular boot steps
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/boot
  dietpi/preboot
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:

#2884 DietPi-Software | O!MPD: Install current master + fixes
  .conf/dps_129/lighttpd.ompd.conf
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:

#2889 DietPi-Software | PHP: On ARMv6 add libcurl4-openssl-dev to be pulled from Buster repo
  dietpi/dietpi-software
  dietpi/pre-patch_file
Labels: ARMv6, Bug :beetle:

#2902 DietPi-Drive_Manager | I/O Scheduling: Add option to change I/O scheduler for single drives
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Feature Request :factory:

#2903 DietPi-Software | Ampache: Fix wrong database password and reinstall improvements
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#2904 DietPi-Config | Add option to disable APT cache or move cache, lists and downloads to RAM
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Enhancement :dash:, Feature Request :factory:

#2907 General | Resolve some visual quirks
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
Labels: Enhancement :dash:, Visual :rose:

#2908 DietPi-Software | Medusa: Install FFmpeg and mediainfo as deps and use Python3
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#2917 DietPi-Software | Desktops: Fix PolicyKit error when logging in via LightDM as non-root
  CHANGELOG.txt
  dietpi/dietpi-login
Labels: Bug :beetle:

#2918 DietPi-Software | Transmission: Fix web UI settings not being persistent
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#2920 DietPi-Config | Update I-Sabre-Q2M sound card selection
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Enhancement :dash:, RPi

#2930 DietPi-Autostart | Allow to define a login user for all autologin options
  CHANGELOG.txt
  dietpi.txt
Labels: Enhancement :dash:, Feature Request :factory:

#2933 Image | ROCK Pi 4: Initial definition
  .meta/dietpi-survey_report
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:

#2931 DietPi-Software | Add Mycroft AI Open Source Voice Assistant as install option
  CHANGELOG.txt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Software Request :cd:

#2934 Beta v6.25.0
  .conf/desktop/apps/dietpi-process_tool.desktop
  .conf/desktop/apps/dietpi-services.desktop
  .conf/dps_129/lighttpd.ompd.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/boot
  dietpi/dietpi-autostart
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-launcher
  dietpi/dietpi-login
  dietpi/dietpi-process_tool
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/func/obtain_network_details
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/dietpi-nordvpn
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/preboot
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta

#2940 Beta v6.25.1
  .conf/dps_176/mycroft.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta
