Repository MichaIng/DietPi, pull requests merged in 2019-09, with the labels that each got.

#3086 DietPi-Software | TigerVNC: Resolve immediate coredump on connect + other minor issues
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, External Bug :beetle:

#3091 DietPi-Software | Netdata: Fix install on Stretch
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Debian Stretch, External Bug :beetle:

#3095 Time sync | Avoid concurrent DietPi-Run_NTPD executions
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_software
  dietpi/func/run_ntpd
Labels: Bug :beetle:, Enhancement :dash:

#3084 NordVPN improvements | Change up and down script and add item to DietPi-Banner
  dietpi/func/dietpi-banner
  dietpi/misc/dietpi-nordvpn
Labels: Enhancement :dash:, Feature Request :factory:

#3110 DietPi-Software | myMPD: Update installer to satisfy current release
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3092 DietPi-Software | Kodi: Fix install on RPi Buster via 3rd party repo/builds
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/misc/start_kodi
Labels: Debian Buster, External Bug :beetle:, RPi, RPi4

#3087 Rock(Pro)64 | Workaround kernel-based Ethernet issues
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/patch_file
Labels: External Bug :beetle:, Rock64, RockPro64, Testing/testers required :arrow_down_small:

#3114 General | Fix external keyboard layout bug on Buster
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Debian Buster, External Bug :beetle:

#3119 Dietpi-Imager | FIx formula to get starting sector of root partition
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3125 dietpi-imager | Simplify command
  .meta/dietpi-imager
Labels: Coding :bookmark_tabs:, Enhancement :dash:, META
