Repository MichaIng/DietPi, pull requests merged in 2019-10, with the labels that each got.

#3142 README.md | Add Clonezilla to Additional Software list
  README.md
Labels: META

#3141 Beta v6.26.1
  CHANGELOG.txt
  README.md
  dietpi/boot
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/postboot
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Beta

#3154 Ready | DietPi-Software | update gitea to 1.9.4
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3146 dietpi-image | Fix trying to reduce partition size to a not smaller size
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3136 dietpi-imager | Sanetize list of selectable drives
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3145 Beta v6.26.2
  .meta/dietpi-imager
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  config.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta

#3155 Beta v6.26.3
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Beta

#3161 CHANGELOG | Set release date and add known issue with MATE desktop root login
  CHANGELOG.txt
Labels: META

#3163 CHANGELOG | Set release PR link
  CHANGELOG.txt
Labels: META

#3168 dietpi-installer | Replace fdisk/gdisk by sfdisk/sgdisk
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3171 DietPi-Autostart | Correction of small typo in Game title "Rebirth"
  .conf/dps_114/nginx.nextcloud.conf
  dietpi/dietpi-autostart
Labels: Visual :rose:

#3169 DietPi-Software | ownCloud: Enable v10.3 install with PHP7.3
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3195 Update dietpi-imager
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3198 Update dietpi-imager
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3199 Update dietpi-imager
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3204 Nginx + php-fpm security fix
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_47/nginx.owncloud.conf
Labels: External Bug :beetle:, Security :lock:

#3192 DietPi-Obtain_network_details | Active interface estimation fallback
  dietpi/func/obtain_network_details
Labels: Enhancement :dash:

#3193 DietPi-Software | NAA Daemon: Always grab latest package from website
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3200 Update dietpi-imager
  .meta/dietpi-imager
Labels: Enhancement :dash:, META

#3202 DietPi-Software | Syncthing: Fix permission issue and rework installer
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:

#3212 Update dietpi-imager
  .meta/dietpi-imager
Labels: META
