Repository MichaIng/DietPi, pull requests merged in 2020-06, with the labels that each got.

#3605 DietPi-Software | Ubooquity: Version update, logs and permissions
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3617 General | Add Raspberry Pi OS (64-bit) support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/patch_file
  dietpi/pre-patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: ARMv8, Image Request :floppy_disk:, RPi

#3620 DietPi-Software | WireGuard: Further SBC support and symlink workaround
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Software Request :cd:

#3621 Beta v6.31.0
  .conf/dps_2/config.xml
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .conf/dps_96/conf
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_xu4.ini
  dietpi.txt
  dietpi/boot
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-led_control
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/change_hostname
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/sysctl.d/dietpi.conf
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#3629 Update BRANCH_SYSTEM.md
  BRANCH_SYSTEM.md
Labels: META

#3631 Overclocking | Fix RPi3+ models detection
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Bug :beetle:, RPi
