Repository MichaIng/DietPi, pull requests merged in 2020-09, with the labels that each got.

#3762 DietPi-Globals | Remove G_FP_DIETPI_USERDATA variable
  .conf/dps_176/mycroft.conf
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_userdata
  dietpi/patch_file
Labels: Enhancement :dash:

#3768 DietPi-Login/Autostart | Some fixes and enhancements
  .conf/dps_51/run
  CHANGELOG.txt
  dietpi/dietpi-login
Labels: Bug :beetle:, Enhancement :dash:

#3781 Add new dependency "libjpeg-dev" for HA
  dietpi/dietpi-software
Labels: ARMbaby, Bug :beetle:

#3780 DietPi-Software | Make "dietpi" the primary group for certain services
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3784 DietPi-Software | Tautulli: Switch to Python 3 + further updates
  CHANGELOG.txt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3789 DietPi-Software | Some enhancement for Baikal
  .conf/dps_57/apache.baikal.conf
  .conf/dps_57/lighttpd.baikal.conf
  .conf/dps_57/nginx.baikal.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3791 DietPi-Software | Docker: Log to journald + reduce log level
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3794 DietPi-Software | Mosquitto: Use official APT repository where available
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3795 DietPi-Software | Cuberite: Rename directory from typo "cubrite" to intended "cuberite"
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3800 DietPi-Software | TigerVNC+LXDE: Fix lxappearance launch from within TigerVNC LXDE session
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Known Issue :bug:
