Repository MichaIng/DietPi, pull requests merged in 2020-02, with the labels that each got.

#3368 DietPi Patreon Legend
  dietpi/func/dietpi-banner
Labels: META, Priority High :high_brightness:

#3366 New DietPi Patreon Legend
  dietpi/func/dietpi-banner
Labels: META, Priority High :high_brightness:

#3367 DietPi Patreon Legend
  dietpi/func/dietpi-banner
Labels: META, Priority High :high_brightness:

#3375 DietPi-Drive_Manager | Preserve glusterfs fstab entries
  dietpi/dietpi-drive_manager
Labels: Feature Request :factory:

#3379 NanoPi M4v2 | Add initial definition and support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/func/dietpi-obtain_hw_model
  rootfs/etc/network/if-up.d/dietpi-disable_offload
Labels: Image Request :floppy_disk:

#3383 DietPi-Software | MPD and myMPD: Several smaller updates
  .conf/dps_128/mpd.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#3387 Images | Add Pine H64 and ROCK Pi S support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:

#3349 DietPi-Software | Sonarr/Radarr/Lidarr: Several enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3397 DietPi-LED_control | Major rework
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-led_control
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-led_control
  dietpi/func/dietpi-obtain_hw_model
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/preboot
  rootfs/etc/bashrc.d/dietpi.bash
Labels: Enhancement :dash:
