Repository MichaIng/DietPi, pull requests merged in 2020-10, with the labels that each got.

#3807 DietPi-Software | Firefox Sync Server: Fix broken install due to started Rust migration
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#3813 DietPi-Software | Enhancement Fail2Ban
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Security :lock:

#3814 Beta v6.33.1
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta :test_tube:

#3827 Beta v6.33.2
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#3834 DietPi-Software | LXDE: Execute desktop icons and executable files directly without asking what to do
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3830 Beta v6.33.3
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/server_version-6
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#3845 DietPi-Software | Show output of PiVPN installer
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#3843 DietPi-Update | update medusa service
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#3855 DietPi-Bugreport | Do URL check against SFTP/SSH port
  CHANGELOG.txt
  dietpi/dietpi-bugreport
Labels: Enhancement :dash:

#3848 DietPi-Software | OpenBazaar: Updates and enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3854 DietPi-Software | Add Config Creation function
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3865 DietPi-Software | Lighttpd: Fix lighty-enable-mod "failing" with exit code 2
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#3828 DietPi-Software | Paper MC Server
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#3868 DietPi-Software | PaperMC: Add changelog and survey report entry
  .meta/dietpi-survey_report
  CHANGELOG.txt
Labels: Software Request :cd:

#3870 DietPi-Set_swapfile | Enhance zram-swap hardening and input tolerance
  CHANGELOG.txt
  dietpi/func/dietpi-set_swapfile
Labels: Enhancement :dash:
