Repository MichaIng/DietPi, pull requests merged in 2020-08, with the labels that each got.

#3701 DietPi-Boot | Service output enhancements
  .meta/dietpi-fan_control
  .shellcheckrc
  dietpi/boot
  dietpi/dietpi-backup
  dietpi/dietpi-sync
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/func/run_ntpd
  dietpi/postboot
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
Labels: Coding :bookmark_tabs:, Enhancement :dash:, Visual :rose:

#3713 NanoPi NEO3 | Add initial support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:, NanoPi NEO3

#3714 DietPi-Set_swapfile | Add simple support for a zram swap space
  CHANGELOG.txt
  dietpi.txt
  dietpi/func/dietpi-set_swapfile
Labels: Feature Request :factory:

#3720 DietPi-Software | change ownership for /var/www/wordpress/
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3728 DietPi-LetsEncrypt | Initial Lighttpd-only support for multiple comma-separated domains
  dietpi/dietpi-letsencrypt
Labels: Feature Request :factory:

#3731 DietPi-Software | Komga: FOSS home server for comics and ebooks library
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#3734 DietPi-LetsEncrypt | Lighttpd: Config updates
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Enhancement :dash:

#3721 Create SECURITY.md
  SECURITY.md
Labels: META, Security :lock:

#3643 DietPi-Config | Remove deprecated max_usb_current option
  CHANGELOG.txt
  config.txt
  dietpi/dietpi-config
  dietpi/patch_file
Labels: RPi

#3735 DietPi-Software | HTPC Manager: Migrate to Python3-compatible fork
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3742 General | Add initial support for NanoPi R2S and NanoPi K2
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:

#3733 Beta v6.32.0
  .conf/desktop/icons/dietpi-icon.png
  .conf/desktop/icons/justboom.png
  .conf/desktop/icons/kodi-icon.png
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_6/xorg_c2.conf
  .conf/dps_85/nginx.conf
  .conf/dps_93/apache.pihole.conf
  .conf/dps_94/conf
  .gitattributes
  .gitignore
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .meta/images/76mm_rounder_sticker.png
  .meta/images/dietpi-background_480p.png
  .meta/images/dietpi-logo_inverted.png
  .shellcheckrc
  CHANGELOG.txt
  CONTRIBUTING.md
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  SECURITY.md
  config.txt
  dietpi.txt
  dietpi/boot
  dietpi/dietpi-backup
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/func/dietpi-set_userdata
  dietpi/func/run_ntpd
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/postboot
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/etc/apt/apt.conf.d/97dietpi
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/bashrc.d/readme.txt
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#3744 DietPi-Set_swapfile | correct information
  dietpi/func/dietpi-set_swapfile
Labels: META

#3748 Update dietpi-config
  dietpi/dietpi-config
Labels: META

#3747 Beta v6.32.1
  .meta/dietpi-cloud-migration
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .shellcheckrc
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_swapfile
  dietpi/pre-patch_file
  dietpi/server_version-6
Labels: Beta :test_tube:

#3750 Beta v6.32.2
  .shellcheckrc
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/misc/start_kodi
  dietpi/server_version-6
Labels: Beta :test_tube:
