Repository MichaIng/DietPi, pull requests merged in 2020-12, with the labels that each got.

#3945 DietPi-Software | Radarr: Migrate to .NET core version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3949 DietPi-Software | OctoPrint: Switch to now available PyPI repo install
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:, Enhancement :dash:

#3921 DietPi-Software | Tor Relay
  dietpi/dietpi-cloudshell
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#3951 DietPi-Software | Move WiFi Hotspot to Advanced Networking
  dietpi/dietpi-software
Labels: META

#3933 DietPi-Software | Add Portainer
  dietpi/dietpi-software
Labels: Software Request :cd:

#3953 DietPi-JustBoom | Move ALSA equalizer config to world-readable location
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
Labels: Enhancement :dash:

#3938 DietPi-Config | Fix RPi onboard audio selection
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Bug :beetle:, RPi

#3956 DietPi-Software | Ampache - change Composer
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#3960 Beta v6.34.0
  .conf/dps_176/mycroft.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-optimal_mtu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-justboom
  dietpi/misc/dietpi-nordvpn
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/etc/apt/apt.conf.d/97dietpi
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#3964 DietPi-Software | Fix Tor Relay IPv6 Detection
  dietpi/dietpi-software
Labels: Bug :beetle:

#3965 DietPi-Software | Fix Tor relay configuration
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#3967 DietPi-Software | Ampache - Change ownership on web server root directory
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:

#3968 Beta v6.34.1
  .conf/dps_121/roonbridge.service
  .shellcheckrc
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/cron.daily/dietpi
Labels: Beta :test_tube:

#3974 DietPi-CloudShell | Several enhancements
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-cloudshell
  dietpi/dietpi-launcher
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/patch_file
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-cloudshell.service
Labels: Enhancement :dash:

#3969 DietPi-CloudShell | Run nyx on a separate TTYl
  dietpi/dietpi-cloudshell
Labels: Enhancement :dash:

#3980 Link to FeatHub base page added
  README.md
Labels: Enhancement :dash:, META

#3979 DietPi-Software | OctoPrint: Migrate to user-level Python instance
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Bug :beetle:

#3981 Beta v6.34.2
  .meta/dietpi-survey_report
  .meta/images/dietpi-logo_150.png
  .meta/myip.php
  CHANGELOG.txt
  README.md
  dietpi/dietpi-autostart
  dietpi/dietpi-cloudshell
  dietpi/dietpi-launcher
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/systemd/system/dietpi-cloudshell.service
Labels: Beta :test_tube:

#3983 DietPi-Software | Desktops: Replace DietPi desktop icon with transparent one
  .conf/desktop/icons/dietpi-icon.png
  dietpi/dietpi-software
Labels: Enhancement :dash:

#3984 Beta v6.34.3
  .conf/desktop/icons/dietpi-icon.png
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/server_version-6
Labels: Beta :test_tube:

#3982 Release v6.34
  .conf/desktop/icons/dietpi-icon.png
  .conf/dps_121/roonbridge.service
  .conf/dps_176/mycroft.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .meta/images/dietpi-logo_150.png
  .meta/myip.php
  .shellcheckrc
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-launcher
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-optimal_mtu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-justboom
  dietpi/misc/dietpi-nordvpn
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version-6
  rootfs/etc/apt/apt.conf.d/97dietpi
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/systemd/system/dietpi-cloudshell.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Information :information_source:

#3988 Prepare v6.35 version string and changelog
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/func/dietpi-globals
  dietpi/server_version-6
Labels: META

#3995 DietPi-Software | Fix GITOWNER when installing desktops
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4006 DietPi-Software | Portainer enhancement
  dietpi/dietpi-software
Labels: Enhancement :dash:
