Repository MichaIng/DietPi, pull requests merged in 2020-05, with the labels that each got.

#3497 DietPi-Drive_Manager | Fix handling mount sources and targets with spaces
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Bug :beetle:

#3501 Beta v6.29.2
  .github/FUNDING.yml
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/server_version-6
Labels: Beta

#3517 Beta v6.30.0
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/boot
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/tmpfiles.d/dietpi.conf
Labels: Beta

#3471 DietPi-Software | Add Firefox Sync Server
  dietpi/dietpi-software
Labels: Software Request :cd:

#3531 DietPi-Software | rTorrent: Fix default config
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Via Forum

#3536 DietPi-Software | Firefox Sync Server polish
  CHANGELOG.txt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3545 Odroid C4 | Add initial support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/misc/start_kodi
Labels: Image Request :floppy_disk:, Odroid C4

#3546 DietPi-Software | Folding@Home: Update to new v7.6 and minor install enhancements
  .conf/dps_2/config.xml
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/patch_file
Labels: Enhancement :dash:

#3565 DietPi-Logclear | Resolve an issue where .db-shm and .db-wal files are were not excluded from processing
  CHANGELOG.txt
  dietpi/func/dietpi-logclear
Labels: Bug :beetle:
