Repository MichaIng/DietPi, pull requests merged in 2021-05, with the labels that each got.

#4324 DietPi-Software | WiringPi: Migrate to new RPi Git branch
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, RPi

#4329 DietPi-Software | Python3
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#4337 DietPi-LetsEncrypt | Lighttpd: Resolve lighty-*-mod errors
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Bug :beetle:

#4331 DietPi-Software | Webmin: Add support for internal restart
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#4340 DietPi-Drive_Manager | Fix NTFS detection and mounting
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Bug :beetle:

#4342 DietPi-Software | Docker Compose: Fix install on ARMv8 + Stretch
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv8, Bug :beetle:, Debian Stretch

#4326 DietPi-Software | WiringPi: Enable support for selected NanoPi models
  dietpi/dietpi-software
Labels: Enhancement :dash:, FriendlyARM, NanoPi M1/T1, NanoPi NEO, NanoPi NEO Air, NanoPi NEO2

#4347 DietPi-VPN | On reset, offer to purge OpenVPN
  CHANGELOG.txt
  dietpi/dietpi-vpn
Labels: Enhancement :dash:

#4351 DietPi-Software | Radarr
  dietpi/dietpi-software
Labels: Bug :beetle:

#4332 DietPi-Software | rTorrent
  dietpi/dietpi-software
Labels: Bug :beetle:

#4345 DietPi-Software | Node.js: Use unofficial builds on ARMv6
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv6, Bug :beetle:, Enhancement :dash:, RPi

#4349 DietPi-Drive_Manager | Fix issues with autofs drives
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/patch_file
Labels: Bug :beetle:

#4362 DietPi-Software | Kodi
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4364 DietPi-Software | Home Assistant: Fix install as "pyenv init -" does not set PATH anymore
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4366 DietPi-JustBoom | Fix equalizer
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Bug :beetle:, Via Forum

#4363 DietPi-Software | RPi Cam Control: Disable for 64-bit images
  .conf/dps_59/raspimjpeg.sh
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv8, Bug :beetle:, RPi

#4343 Pinebook Pro | Add initial support
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:, PREP :diamond_shape_with_a_dot_inside:, Pinebook Pro

#4314 DietPi-Software | Rework dependency and choice system
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-software
Labels: Coding :bookmark_tabs:, Feature Request :factory:

#4386 DietPi-Software | Refactoring
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Coding :bookmark_tabs:, Enhancement :dash:

#4388 DietPi-Patches | Patch version-based and remove LibSSL1.0.0 flag
  .update/patches
Labels: Enhancement :dash:

#4390 DietPi-AutoStart | Enable desktop autologin for unprivileged users via LightDM
  CHANGELOG.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-login
Labels: Enhancement :dash:, Feature Request :factory:

#4394 Image | NanoPi R4S and NanoPi R1
  .meta/dietpi-survey_report
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/func/dietpi-obtain_hw_model
Labels: FriendlyARM, Image Request :floppy_disk:, NanoPi R1, NanoPi R4S

#4398 DietPi-Banner/VPN | Move to more reliable WAN IP + location API service
  CHANGELOG.txt
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
Labels: Enhancement :dash:, External Bug :beetle:

#4399 DietPi-Software | Update Roon Extension Manager to v1.0
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4403 DietPi-Patches | Roon Extension Manager: Inform user about upgrade
  .update/patches
  CHANGELOG.txt
Labels: Enhancement :dash:

#4405 DietPi-Software | Pi-hole: Whitelist GEO IP API we use in banner and DietPi-VPN
  .update/patches
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4404 DietPi-DDNS | Add support for FreeDNS: https://freedns.afraid.org/
  CHANGELOG.txt
  dietpi/dietpi-ddns
Labels: Enhancement :dash:

#4407 DietPi-VPN | Add native support for further providers
  CHANGELOG.txt
  dietpi/dietpi-vpn
Labels: Feature Request :factory:

#4406 Beta v7.2.0
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_59/raspimjpeg.sh
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_xu4.ini
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#4412 DietPi-Software | Update hardcoded software versions
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4415 Beta v7.2.1
  .conf/dps_6/xorg_pine64.conf
  .update/version
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-backup
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-set_swapfile
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#4425 DietPi-Software | Mosquitto: Fix install on ARMv8
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv8, Bug :beetle:

#4430 DietPi-Software | Pi-hole: Reduce default logging TTL to 2 days
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4431 DietPi-DDNS | Add native support for OVH
  CHANGELOG.txt
  dietpi/dietpi-ddns
Labels: Enhancement :dash:

#4423 Beta v7.2.2
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi/dietpi-ddns
  dietpi/dietpi-morsecode
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/patch_file
Labels: Beta :test_tube:

#4432 DietPi-Start_Kodi | On RPi 64-bit systems, do not try to start Kodi without X server
  CHANGELOG.txt
  dietpi/misc/start_kodi
Labels: ARMv8, Bug :beetle:, RPi

#4437 Beta v7.2.3
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/misc/start_kodi
Labels: Beta :test_tube:

#4422 Release v7.2
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_59/raspimjpeg.sh
  .conf/dps_6/xorg_pine64.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_xu4.ini
  config.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/change_hostname
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/start_kodi
  dietpi/patch_file
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Information :information_source:

#4439 Init v7.3
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#4440 Update AdGuardHome branch
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/misc/start_kodi
Labels: META

#4441 Update beets branch
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#4442 Update frp branch
  .conf/dps_6/xorg_pine64.conf
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-morsecode
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/change_hostname
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/start_kodi
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: META

#4446 DietPi-Software | Fix ipfs command when called from non-root user
  .update/patches
  dietpi/func/dietpi-set_software
Labels: Bug :beetle:

#4448 DietPi-JustBoom | Fix false equalizer detection
  CHANGELOG.txt
  dietpi/misc/dietpi-justboom
Labels: Bug :beetle:
