Repository MichaIng/DietPi, pull requests merged in 2021-02, with the labels that each got.

#4039 DietPi-Sotware | PaperMC
  dietpi/dietpi-software
Labels: Bug :beetle:

#4079 DietPi-Software | WiringPi
  dietpi/dietpi-software
Labels: Bug :beetle:

#3989 DietPi-Software | Box86 and Steam for armhf
  dietpi/dietpi-software
Labels: Software Request :cd:

#4015 Apply desktop Customisations to all users
  dietpi/dietpi-autostart
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4084 DietPi-Software | Add Box86 and Docker Compose meta info
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
Labels: META

#4086 DietPi-Software | Migrate documentation URLs
  dietpi/dietpi-software
Labels: Enhancement :dash:, META

#4090 Comment changed from dietpi.com/phpBB to dietpi.com/docs
  dietpi.txt
  dietpi/dietpi-survey
Labels: Enhancement :dash:

#4091 DietPi-Software | Add mjpg-streamer install option
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Feature Request :factory:, Software Request :cd:

#4094 Fix DietPi-Drive_Manager when 'cancel' is selected on the drive list
  dietpi/dietpi-backup
Labels: Bug :beetle:, Enhancement :dash:

#4096 DietPi-Software | Domoticz
  dietpi/dietpi-software
Labels: Bug :beetle:

#4095 DietPi-Software | Several enhancements
  .conf/desktop/gtk/.gtk-bookmarks
  .conf/desktop/lxde/panel
  .conf/dps_59/raspimjpeg.sh
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
Labels: Enhancement :dash:

#4100 DietPi-CloudShell | Fix and simplify obtaining Pi-hole stats
  dietpi/dietpi-cloudshell
Labels: Bug :beetle:, Enhancement :dash:

#4106 DietPi-Software | Fix and enhance GitHub URL/version auto-detection
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#4107 Update "update" branch
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: META

#4103 DietPi-Update | Apply new update system that allows automatic branch migration
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/patch_file
  dietpi/server_version
Labels: Enhancement :dash:

#4110 Beta v7.0.0
  .conf/desktop/gtk/.gtk-bookmarks
  .conf/desktop/lxde/panel
  .conf/desktop/lxqt/lxqt-buster.7z
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_182/unbound.conf
  .conf/dps_39/minidlna.conf
  .conf/dps_59/raspimjpeg.sh
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/patch_file
  dietpi/server_version
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
Labels: Beta :test_tube:

#4122 Link changed from phpBB to dietpi.com/docs
  dietpi/dietpi-backup
  dietpi/dietpi-sync
Labels: Enhancement :dash:

#4128 Links changed from phpBB to dietpi.com/docs #3
  dietpi/dietpi-cleaner
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:, META

#4124 DietPi-Software | Node-RED: Switch to a local service user install
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4132 Beta v7.0.0
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/patch_file
  dietpi/server_version-6
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
  rootfs/etc/udev/rules.d/10-wifi-disable-powermanagement.rules
Labels: Beta :test_tube:

#4138 DietPi-Config | Add an option to toggle the SPI state
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
Labels: Feature Request :factory:, RPi

#4143 Update restore-boot branch
  .update/pre-patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-set_hardware
  dietpi/pre-patch_file
Labels: META

#4144 Choice of automatic login user appears too often
  dietpi/dietpi-autostart
  dietpi/dietpi-software
Labels: Bug :beetle:

#4112 DietPi-Backup | Add Option to Automatically Restore on First Boot
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:, Feature Request :factory:

#4148 Update "wireguard" branch
  .conf/desktop/gtk/.gtk-bookmarks
  .conf/desktop/icons/dietpi-icon.png
  .conf/desktop/lxde/panel
  .conf/desktop/lxqt/lxqt-buster.7z
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_182/unbound.conf
  .conf/dps_39/minidlna.conf
  .conf/dps_59/raspimjpeg.sh
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .meta/images/dietpi-logo_150.png
  .meta/myip.php
  .update/patches
  .update/pre-patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-launcher
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/dietpi-cloudshell.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
  rootfs/etc/udev/rules.d/10-wifi-disable-powermanagement.rules
Labels: META

#4146 Beta v7.0.1
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  CONTRIBUTING.md
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/pre-patch_file
Labels: Beta :test_tube:

#4150 DietPi-Software | Docker-Compose
  dietpi/dietpi-software
Labels: Beta :test_tube:

#4152 Beta v7.0.2
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#4126 Release v7.0
  .conf/desktop/gtk/.gtk-bookmarks
  .conf/desktop/lxde/panel
  .conf/desktop/lxqt/lxqt-buster.7z
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_182/unbound.conf
  .conf/dps_39/minidlna.conf
  .conf/dps_59/raspimjpeg.sh
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  CONTRIBUTING.md
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/patch_file
  dietpi/pre-patch_file
  dietpi/server_version
  dietpi/server_version-6
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/cron.daily/dietpi
  rootfs/etc/systemd/system/dietpi-boot.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
  rootfs/etc/udev/rules.d/10-wifi-disable-powermanagement.rules
Labels: Information :information_source:
