Repository MichaIng/DietPi, pull requests merged in 2021-07, with the labels that each got.

#4526 DietPi-Software | Matrix Synapse Server
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4554 Update youtube-dl branch
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: META

#4553 DietPi-Software | Split youtube-dl into own software title
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:

#4556 DietPi-Software | Fix PaperMC Floodgate download link
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4558 DietPi-Software | Home Assistant: Use piwheels.org on ARMv6/7
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv6, ARMv7, Enhancement :dash:

#4565 DietPi-Software | myMPD: Update for v8.0.0
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4566 Beta v7.4.0
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_95/conf
  .meta/dietpi-survey_report
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/patch_file
Labels: Beta :test_tube:

#4570 Update Komga new setting for v0.107.0
  dietpi/dietpi-software
Labels: Docs change required, Enhancement :dash:

#4572 DietPi-Update | Live patches via GitHub repository version file
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
Labels: Feature Request :factory:

#4577 Beta v7.4.1
  .update/pre-patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_swapfile
Labels: Beta :test_tube:

#4580 DietPi-Software | Pi-hole: Enable LAN IPv6 access for blocked public admin panel access
  .conf/dps_93/apache.block_public_admin.conf
  .conf/dps_93/lighttpd.block_public_admin.conf
  .conf/dps_93/nginx.block_public_admin.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4583 Beta v7.4.2
  .conf/dps_93/apache.block_public_admin.conf
  .conf/dps_93/lighttpd.block_public_admin.conf
  .conf/dps_93/nginx.block_public_admin.conf
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#4594 DietPi-Software | Blynk Server: Fix install option by switching to fork
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: :wrench: Live patch request, Docs change required, External Bug :beetle:

#4601 Live patch | Fix Blynk server install
  .update/version
Labels: Live patch
