Repository MichaIng/DietPi, pull requests merged in 2021-06, with the labels that each got.

#4474 DietPi-Backup | Address issue always excluded external userdata
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-backup
Labels: Bug :beetle:, Enhancement :dash:

#4429 DietPi-Software | AdGuard Home
  .conf/dps_126/AdGuardHome.yaml
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4411 DietPi-Software | frp
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4438 DietPi-Software | Beets
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:

#4477 Prevent prompt for License Auto-Accept
  dietpi.txt
  dietpi/dietpi-login
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:

#4494 DietPi-Automation | Allow to turn DHCP leased IP as static IP
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-software
Labels: Feature Request :factory:

#4496 DietPi-Software | Add Snapcast Server and Client install options
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4476 DietPi-Software | K3s
  dietpi.txt
  dietpi/dietpi-software
Labels: Software Request :cd:

#4497 DietPi-Software | K3s: Add service handling and meta info
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
Labels: Software Request :cd:

#4495 Beta v7.3.0
  .conf/dps_126/AdGuardHome.yaml
  .meta/dietpi-fan_control
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#4501 DietPi-Software | Remove Tomcat 8
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4513 Update Fallback URLs
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4514 DietPi-Software | AdGuard Home: Install binary to userdata for now
  dietpi/dietpi-software
Labels: Bug :beetle:

#4508 Beta v7.3.1
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/preboot
Labels: Beta :test_tube:

#4517 DietPi-Set_hardware | Add support for the Allo Boss2 OLED display
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
Labels: Feature Request :factory:, RPi

#4516 Beta v7.3.2
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#4520 DietPi-Patches | RPi: Remove deprecated I2C setting from config.txt
  .update/patches
Labels: Bug :beetle:

#4521 Init v7.4
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META
