Repository MichaIng/DietPi, pull requests merged in 2021-04, with the labels that each got.

#4220 DietPi-LetsEncrypt | Add multi-domain + standalone + OCSP + Lighttpd IPv6
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Feature Request :factory:

#4239 DietPi-Software | Portainer
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4223 DietPi-Software | Mosquitto: Updates for v2 and other enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4250 Update PR branch
  .conf/dps_182/unbound.conf
  .conf/dpv/protonvpn.template
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  boot_c2.ini
  boot_n2.ini
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/misc/dietpi-nordvpn
  dietpi/patch_file
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-vpn.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: META

#4252 DietPi-Software | Workaround for 7zr overriding umask for target dir
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4259 DietPi-Software | myMPD
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4166 DietPi-Software | Resolve port conflicts
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:

#4236 DietPi-Software | IPFS Node
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-launcher
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4262 Update DietPi-DDNS branch
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_182/unbound.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dpv/protonvpn.template
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_userdata
  dietpi/misc/dietpi-nordvpn
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-vpn.service
Labels: META

#4255 DietPi-Software | CUPS
  .conf/dps_187/cupsd.conf
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#4269 DietPi-Software | Part 1: Merge "Linux" software and "DietPi" software functions
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4271 DietPi-Software | O!MPD
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4270 DietPi-Software | Part 2: Merge "Optimised" and "Additional" software menus
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4272 DietPi-Software | Make Go an own install option (ID=188)
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Enhancement :dash:, Software Request :cd:

#4276 DietPi-Software | VSCodium
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:

#4229 DietPi-DDNS | Manage domains for your dynamic IP
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  rootfs/etc/bashrc.d/dietpi.bash
Labels: Feature Request :factory:

#4289 Software package name changed from "Python 3 pip" to "Python 3"
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4290 DietPi-Drive_Manager | Move Samba credentials from /etc/fstab to separate per-mount credentials file
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Security :lock:

#4292 DietPi-Software | Sonarr: Migrate to v3
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/misc/dietpi-arr_to_RAM
Labels: Enhancement :dash:

#4288 Beta v7.1.0
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_182/unbound.conf
  .conf/dps_187/cupsd.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dpv/protonvpn.template
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_c2.ini
  boot_n2.ini
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-launcher
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_userdata
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/dietpi-nordvpn
  dietpi/patch_file
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-vpn.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#4297 DietPi-Software | Rework part 3: Category restructure
  dietpi/dietpi-software
Labels: Enhancement :dash:, Priority Low :low_brightness:

#4302 DietPi-Software | OpenBazaar: Switch install method
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4299 Beta v7.1.1
  .meta/dietpi-imager
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-explorer
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#4310 DietPi-Software | WebIOPi: RPi 3/4 support + Python 3
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Bug :beetle:, Enhancement :dash:, RPi

#4308 Beta v7.1.2
  .conf/dps_182/unbound.conf
  .conf/dpv/protonvpn.template
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/dietpi-ddns
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Beta :test_tube:

#4315 DietPi-Tools | dietpi-arr_to_RAM
  dietpi/misc/dietpi-arr_to_RAM
Labels: Bug :beetle:
