Repository MichaIng/DietPi, pull requests merged in 2021-09, with the labels that each got.

#4701 DietPi-Software | Refactoring and alignment
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4723 DietPi-Software | Blynk: Assure that the default log directory exists
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#4724 DietPi-FS_partition_resize | Reboot to reload partition table if partprobe/partx fails
  CHANGELOG.txt
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Enhancement :dash:

#4725 DietPi-Drive_Manager | Native Linux exFAT support and mount modes
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
Labels: Enhancement :dash:, Security :lock:

#4726 DietPi-Software | MPD: Several enhancements
  .conf/dps_128/mpd.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Enhancement :dash:, Debian Bullseye

#4719 DietPi-Software | Kodi: Install our RPi 32-bit Kodi package on all 32-bit RPi images
  dietpi/dietpi-software
Labels: Enhancement :dash:, RPi, Debian Bullseye

#4727 Beta v7.6.0
  .conf/dps_128/mpd.conf
  .github/ISSUE_TEMPLATE/bug_report.md
  .meta/dietpi-build
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/dietpi-backup
  dietpi/dietpi-bugreport
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#4730 DietPi-Software | qBittorrent: Some fixes and enhancements
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Enhancement :dash:

#4625 DietPi-Software | Box64
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:, ARMv8

#4634 DietPi-Login/Autostart | Add autostart option for a custom script to be ran after automatic login.
  dietpi/dietpi-autostart
  dietpi/dietpi-login
Labels: Feature Request :factory:

#4686 DietPi-Software | filebrowser
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#4735 Beta v7.6.1
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-autostart
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/patch_file
Labels: Beta :test_tube:

#4713 DietPi-Software | Add spotifyd
  .conf/dps_199/spotifyd.conf
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#4744 DietPi-Software | File Browser
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4746 Beta v7.6.2
  .conf/dps_199/spotifyd.conf
  .conf/dps_39/minidlna.conf
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#4763 Backwards merge
  .update/version
Labels: META

#4764 DietPi-Live_patch | Fix syntax error in DietPi-LetsEncrypt
  .update/version
Labels: Live patch

#4776 DietPi-Live_patches | Lighttpd Buster migration and Kodi on RPi 64-bit
  .update/version
Labels: Live patch

#4787 DietPi-Software | Deluge: Fix web interface service on Bullseye
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Debian Bullseye

#4789 DietPi-Live_patches | Fix a bug with Deluge on Bullseye
  .update/version
Labels: Live patch
