Repository MichaIng/DietPi, pull requests merged in 2021-08, with the labels that each got.

#4619 DietPi-Software | phpSysInfo
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: :wrench: Live patch request, Bug :beetle:

#4593 DietPi-Software | Java: Split into JDK and JRE and fix ARMv6 install
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: ARMv6, Enhancement :dash:, External Bug :beetle:

#4621 DietPi-Live_patches | Fix phpSysInfo install
  .update/version
Labels: Live patch

#4618 DietPi-Software | Bazarr
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:

#4638 DietPi-Globals | G_GET_WAN_IP: Add function to retrieve the public IP
  CHANGELOG.txt
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:

#4636 DietPi-Software | LXDE: Fix install on RPi Bullseye
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :beetle:, Debian Bullseye, :wrench: Live patch request

#4637 DietPi-Live_patches | Fix LXDE install on RPi Bullseye
  .update/version
Labels: Live patch

#4640 Beta v7.5.0
  .meta/dietpi-build
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  config.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#4660 DietPi-Software | LXQt: Add configuration for Bullseye
  .conf/desktop/lxqt/lxqt-bullseye.7z
  CHANGELOG.txt
Labels: Bug :lady_beetle:, Debian Bullseye

#4659 DietPi-Software | Cuberite: Remove obsolete ARMv6 workaround
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4662 Beta v7.5.1
  .conf/desktop/lxqt/lxqt-bullseye.7z
  .meta/dietpi-build
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#4665 DietPi-Software | Lidarr: Move to .NET based builds where supported
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#4669 Backwards merge master > dev
  .update/version
Labels: META

#4667 Beta v7.5.2
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#4673 Update motioneye branch
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: META

#4675 Init v7.6
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#4676 Update Box64 branch
  .conf/desktop/lxqt/lxqt-bullseye.7z
  .meta/dietpi-build
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-autostart
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: META

#4677 Update WireGuard for ROCK Pi S branch
  .conf/desktop/lxqt/lxqt-bullseye.7z
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_126/AdGuardHome.yaml
  .conf/dps_182/unbound.conf
  .conf/dps_59/raspimjpeg.sh
  .conf/dps_6/xorg_pine64.conf
  .conf/dps_93/apache.block_public_admin.conf
  .conf/dps_93/lighttpd.block_public_admin.conf
  .conf/dps_93/nginx.block_public_admin.conf
  .conf/dps_95/conf
  .conf/dpv/protonvpn.template
  .meta/dietpi-build
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_xu4.ini
  config.txt
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-explorer
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/change_hostname
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/dietpi-justboom
  dietpi/misc/start_kodi
  dietpi/patch_file
  dietpi/preboot
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: META

#4696 DietPi-Live_patches | Fix some LXDE features install on RPi Bullseye
  .update/version
Labels: Live patch

#4698 General | Add initial support for Debian 12 Bookworm
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
Labels: Debian Bookworm
