Repository MichaIng/DietPi, pull requests merged in 2021-12, with the labels that each got.

#5011 DietPi-Software | Kodi: RPi repo package on Bullseye and addons repository
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, RPi

#5015 DietPi-Software | Gitea: Run service as dedicated user "gitea"
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Docs change required

#5016 DietPi-Backup | Backup archive and lifted /mnt limit
  CHANGELOG.txt
  dietpi/dietpi-backup
Labels: Feature Request :factory:

#5017 Beta v7.9.0
  .conf/dps_182/unbound.conf
  .meta/dietpi-build
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  boot_c2.ini
  boot_xu4.ini
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/run_ntpd
  dietpi/patch_file
  rootfs/etc/cron.hourly/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#5028 Beta v7.9.1
  .conf/desktop/apps/dietpi-justboom.desktop
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  config.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/misc/dietpi-justboom
Labels: Beta :test_tube:

#5037 Beta v7.9.2
  .update/version
  CHANGELOG.txt
  boot_n2.ini
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#5052 Beta v7.9.3
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#5065 DietPi-Live-patch | Fix Docker install
  .update/version
Labels: Live patch

#5091 DietPi-Live_patches | Fix forced max frequencies on Raspberry Pi
  .update/version
Labels: RPi, Live patch

#5068 Debian Stretch code removal party
  .conf/dps_121/roonbridge.service
  .meta/dietpi-imager
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/etc/systemd/system/dietpi-vpn.service
  rootfs/etc/systemd/system/dietpi-wifi-monitor.service
Labels: Enhancement :dash:, Docs change required

#5099 DietPi-Software | Mono: Install only "mono-devel" instead of "mono-complete"
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5102 DietPi-Software | FuguHub: Use systemd unit a.o. resolve uninstall issue
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Enhancement :dash:, Docs change required

#5109 Software Nextcloud: Fix php.ini entry of memory_consumption
  dietpi/dietpi-software
Labels: Bug :lady_beetle:
