Repository MichaIng/DietPi, pull requests merged in 2022-12, with the labels that each got.

#5944 DietPi-Software | myMPD: Update for upstream change
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Docs change required, Upstream change

#5947 DietPi-Software | Major line reduction
  dietpi/dietpi-software
Labels: Coding :bookmark_tabs:

#5961 Image | Add support for NanoPi R6S
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Image Request :floppy_disk:

#5960 DietPi-Software | RPi Cam Web Interface: Rename project and remove motion dependency
  .conf/dps_59/raspimjpeg.sh
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5984 Beta v8.12.1
  .build/software/vaultwarden/build.bash
  .shellcheckrc
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/misc/dietpi-arr_to_RAM
Labels: Beta :test_tube:

#5985 Release v8.12
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/dps_59/raspimjpeg.sh
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  .shellcheckrc
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-sync
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-wifidb
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/patch_file
  rootfs/etc/sysctl.d/dietpi.conf
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Release

#5991 DietPi-Software | myMPD
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#5993 DietPi-Software | Readarr
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Live patch request :wrench:

#5996 Live patch 0 | Fix Readarr installation
  .update/version
Labels: Live patch

#6014 DietPi-Software | Docker: Fix install if nftables is not supported
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:
