Repository MichaIng/DietPi, pull requests merged in 2022-03, with the labels that each got.

#5328 DietPi-Software | Allo GUI: Major rework
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Enhancement :dash:, Allo GUI, Docs change required

#5329 Beta v8.2.1
  .build/images/dietpi-build
  .meta/dietpi-imager
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#5332 Beta v8.2.2
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
Labels: Beta :test_tube:

#5338 DietPi-Software | Make PHP Composer a dedicated install option
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Software Request :cd:

#5365 DietPi-Software | Mopidy: Fix install
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#4671 DietPi-Software | MotionEye: Enable Python 3 support
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Enhancement :dash:, Bullseye

#5363 DietPi-Drive_Manager | Network drive enhancements
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
Labels: Feature Request :factory:

#5355 DietPi-Banner | Add option to disable credits
  dietpi/func/dietpi-banner
Labels: Feature Request :factory:

#5375 Fix php not executing in rutorrent folder
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#5374 Image | Add support for generic container image
  .build/images/dietpi-build
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_swapfile
  dietpi/func/run_ntpd
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Image Request :floppy_disk:

#5380 DietPi-Software | TasmoAdmin: Move from master to release
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5377 Beta v8.3.0
  .build/images/dietpi-build
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_swapfile
  dietpi/func/run_ntpd
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/ifupdown-pre.service.d/dietpi.conf
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta :test_tube:
