Repository MichaIng/DietPi, pull requests merged in 2022-04, with the labels that each got.

#5383 CI | Add shellcheck to GitHub actions
  .github/workflows/dietpi-build.yml
  .github/workflows/shellcheck.yml
  .shellcheckrc
  dietpi/dietpi-backup
  dietpi/func/change_hostname
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-ramlog
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_userdata
  dietpi/func/dietpi-wifidb
  dietpi/func/run_ntpd
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: META, Coding :bookmark_tabs:

#5393 Beta v8.3.1
  .github/workflows/dietpi-build.yml
  .github/workflows/shellcheck.yml
  .shellcheckrc
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-ramlog
  dietpi/func/dietpi-set_cpu
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_userdata
  dietpi/func/dietpi-wifidb
  dietpi/func/run_ntpd
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta :test_tube:

#5402 CI | Re-enable all optional shellcheck checks
  .build/images/dietpi-build
  .conf/dps_51/run
  .github/workflows/shellcheck.yml
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .shellcheckrc
  .update/patches
  .update/version
  PREP_SYSTEM_FOR_DIETPI.sh
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/func/dietpi-wifidb
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/postboot
  dietpi/pre-patch_file
Labels: Coding :bookmark_tabs:

#5416 DietPi-Software | Chromium: Fix install on RPi Buster
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, RPi, Buster

#5436 DietPi-Software | VirtualHere: Several little enhancements
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5447 DietPi-Config | Add option to toggle APT list compression
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_software
Labels: Feature Request :factory:

#5450 DietPi-Software | rTorrent: Reinstall ruTorrent cleanly
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5451 DietPi-Software | Turn preference choices into ondemand choices
  .update/patches
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5440 Beta v8.4.0
  .build/images/dietpi-build
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_51/run
  .github/workflows/shellcheck.yml
  .meta/dietpi-fan_control
  .meta/dietpi-imager
  .meta/dietpi-survey_report
  .shellcheckrc
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-cron
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/dietpi-update
  dietpi/dietpi-vpn
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/func/dietpi-wifidb
  dietpi/misc/dietpi-arr_to_RAM
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/postboot
  dietpi/pre-patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#5459 Beta v8.4.1
  .build/images/OdroidC1/boot.ini
  .build/images/OdroidXU4/boot.ini
  .build/images/U-Boot/dietpi-initramfs_cleanup
  .build/images/dietpi-build
  .update/patches
  .update/version
  CHANGELOG.txt
  PREP_SYSTEM_FOR_DIETPI.sh
  boot_xu4.ini
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#5464 DietPi-Build | Image build related script and config cleanup
  .build/images/RPi/config.txt
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  boot_c2.ini
  boot_n2.ini
  boot_xu4.ini
  dietpi/dietpi-drive_manager
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
Labels: Installer :diamond_shape_with_a_dot_inside:, Docs change required

#5465 DietPi-Software | OpenBazaar: Remove software option
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Docs change required

#5466 Beta v8.4.2
  .build/images/RPi/config.txt
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  boot_c2.ini
  boot_n2.ini
  boot_xu4.ini
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
Labels: Beta :test_tube:
