Repository MichaIng/DietPi, pull requests merged in 2022-05, with the labels that each got.

#5475 Add Contributor Covenant Code of Conduct
  CODE_OF_CONDUCT.md
Labels: META

#5496 DietPi-Software | WiringPi: Fix install on Odroids
  CHANGELOG.txt
  dietpi/dietpi-cleaner
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Odroids/Meveric

#5481 DietPi-Software | Amiberry: Update to latest version
  .build/software/Amiberry/build.bash
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#5495 DietPi-Software | Prowlarr
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#5509 Security | Allow applying SSH key and disable password logins
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Security :lock:

#5510 Beta v8.5.0
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  CODE_OF_CONDUCT.md
  README.md
  dietpi.txt
  dietpi/dietpi-cleaner
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#5517 CI | Add workflow for building Amiberry packages
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
Labels: CI

#5519 Subprocess-less sleep for dietpi-wifi-monitor.sh
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Enhancement :dash:

#5520 chore: Set permissions for GitHub actions
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/shellcheck.yml
Labels: Security :lock:, CI

#5523 Move subprocess-less sleep to dietpi-globals and use it in other scripts
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/run_ntpd
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Enhancement :dash:

#5521 Beta v8.5.1
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  CONTRIBUTING.md
  README.md
  dietpi/dietpi-bugreport
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-vpn
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/run_ntpd
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Beta :test_tube:

#5524 DietPi-Imager | Install Clonezilla 5.x package only if the repository package appears to be older
  .build/images/dietpi-imager
Labels: Enhancement :dash:

#5525 DietPi-FirstBoot | Call "dietpi-set_software disable_ssh_password_logins" without argument, which applies the dietpi.txt setting internally
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:

#5522 Release v8.5
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  dietpi.txt
  dietpi/dietpi-bugreport
  dietpi/dietpi-cleaner
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-morsecode
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-survey
  dietpi/dietpi-vpn
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-benchmark
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  dietpi/func/run_ntpd
  dietpi/patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/dietpi-wifi-monitor.sh
Labels: Release

#5526 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: CI

#5528 CI | Add dependabot config for workflow updates
  .github/dependabot.yml
Labels: CI

#5529 CI | Backport dependabot config for workflow updates
  .github/dependabot.yml
Labels: CI
