Repository MichaIng/DietPi, pull requests merged in 2023-09, with the labels that each got.

#6587 DietPi-Software | ADS-B Feeder: track airplanes using SDRs and feed the data to ADS-B aggregators
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#6602 DietPi-Imager | Add option to add FAT partition after rootfs to simplify setup
  .build/images/dietpi-build
  .build/images/dietpi-imager
  CHANGELOG.txt
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Feature Request :factory:

#6591 DietPi-Imager | Move from 7z to xz for image compression
  .build/images/dietpi-build
  .build/images/dietpi-imager
  CHANGELOG.txt
Labels: META

#6617 Images | Add SHA256 hashes for every uploaded image archive
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .github/workflows/dietpi-build.yml
Labels: META

#6623 Images | Add GPG signatures to all image uploads
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .github/workflows/dietpi-build.yml
  CHANGELOG.txt
Labels: META, Security :lock:

#6624 Beta v8.22.0
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/shairport-sync/build.bash
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/shellcheck.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#6628 Beta v8.22.1
  .build/images/dietpi-installer
  .build/software/raspberrypi-sys-mods/build.bash
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6610 DietPi-Software | Kavita: An open-source comics/mangas/ebooks with a built-in web reader
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#6630 Beta v8.22.2
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6632 Beta v8.22.3
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-installer
  .github/workflows/dietpi-software.bash
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6626 Release v8.22
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Release :champagne:

#6639 CI | DietPi-Build: Re-enable Trixie/Sid builds
  .build/images/dietpi-build
Labels: CI
