Repository MichaIng/DietPi, pull requests merged in 2023-01, with the labels that each got.

#6024 DietPi-Software | UrBackup: Several setup updates
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Docs change required

#6016 Beta v8.13.0
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  rootfs/etc/sysctl.d/dietpi.conf
Labels: Beta :test_tube:

#6051 v8.13
  .update/pre-patches
Labels: Beta :test_tube:

#6061 Beta v8.13.2
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6053 Release v8.13
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/change_hostname
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  rootfs/etc/sysctl.d/dietpi.conf
Labels: Release

#6066 Live patch 0 | Fix Portainer and Roon Extension Manager installs
  .update/version
Labels: Live patch

#6075 Live patch 1 v8.13
  .update/version
Labels: Live patch, Bookworm

#6099 Add support opi5
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Image Request :floppy_disk:, Docs change required

#6105 DietPi-Software | Koel: Install fixed v5.1.14 on PHP 7.x distro versions
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6103 META | Add script for distro upgrade to Bookworm
  .meta/dietpi-bookworm-upgrade
Labels: Bookworm, Distro upgrade
