Repository MichaIng/DietPi, pull requests merged in 2023-12, with the labels that each got.

#6792 Quartz64 | Kernel and bootloader upgrade
  .github/workflows/quartz64.yml
  .update/patches
  CHANGELOG.txt
Labels: Enhancement :dash:, Quartz64

#6752 DietPi-Software | NZBGet: Migrate to new project maintainer
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Via Forum, Docs change required

#6795 General | Follow symlink with all sed calls on files
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/vaultwarden/build.bash
  .github/workflows/dietpi-software.bash
  .github/workflows/quartz64.yml
  .meta/dietpi-bookworm-upgrade
  .update/patches
  .update/pre-patches
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/pre-patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:, RPi

#6800 Beta v8.25.0
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .build/software/gmediarender/build.bash
  .build/software/gogs/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .build/software/ympd/build.bash
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/dietpi-software.bash
  .github/workflows/quartz64.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-rpi-firmware-migration
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/pre-patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6802 dietpi-rpi-firmware-migration | Add RPi 5 kernel packages
  .meta/dietpi-rpi-firmware-migration
Labels: RPi, RPi 5

#6803 dietpi-rpi-firmware-migration | Fix package name
  .meta/dietpi-rpi-firmware-migration
Labels: Bug :lady_beetle:, RPi, RPi 5

#6807 Beta v8.25.1
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .conf/dps_27/lighttpd.tasmoadmin.3.conf
  .github/workflows/dietpi-build.yml
  .meta/dietpi-rpi-firmware-migration
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6808 Release v8.25
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .build/software/gmediarender/build.bash
  .build/software/gogs/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .build/software/ympd/build.bash
  .conf/dps_114/lighttpd.nextcloud.conf
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_27/lighttpd.tasmoadmin.3.conf
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/quartz64.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-rpi-firmware-migration
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-led_control
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/create_mysql_db
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/misc/dietpi-justboom
  dietpi/patch_file
  dietpi/pre-patch_file
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Release :champagne:

#6810 CHANGELOG | Tiny fix
  CHANGELOG.txt
Labels: META

#6811 CHANGELOG | Tiny fix
  CHANGELOG.txt
Labels: META

#6813 Init v9.0
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  dietpi/func/dietpi-globals
Labels: META

#6821 DietPi-Config | Stress test log
  dietpi/dietpi-config
Labels: Bug :lady_beetle:

#6818 DietPi-Set_Hardware | Update 1st run setup on RPi4
  dietpi/func/dietpi-set_hardware
Labels: Bug :lady_beetle:

#6830 DietPi-Software | motionEye: Update dependencies and switch to pre-release from PyPI
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:
