Repository MichaIng/DietPi, pull requests merged in 2023-11, with the labels that each got.

#6723 Live patch 1 | Fix NFS Server install
  .build/software/dietpi-software-build.bash
  .update/version
Labels: Live patch

#6732 DietPi-Software | openHAB: Switch to stable suite which provides v4 now
  .update/pre-patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6754 Live patch 2 | Prevent installion of conflicting rpi-eeprom package on RPi 4 Bookworm systems
  .update/pre-patches
  .update/version
Labels: Live patch

#6714 DietPi-Software | Nextcloud: Add rewrite rules for Lighttpd
  .conf/dps_114/lighttpd.nextcloud.conf
  CHANGELOG.txt
Labels: Enhancement :dash:, Via Forum

#6761 DietPi-Config | Add SPI toggle for Orange Pi Zero 3
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
Labels: Feature Request :factory:

#6756 Beta v8.24.1
  .build/images/Quartz64/quartz64_defconfig
  .build/images/U-Boot/boot.cmd
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .conf/dps_114/lighttpd.nextcloud.conf
  .github/workflows/armbian.yml
  .meta/dietpi-bookworm-upgrade
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6762 Final commits
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .update/patches
Labels: Beta :test_tube:

#6760 Release v8.24
  .build/images/Quartz64/quartz64_defconfig
  .build/images/U-Boot/boot.cmd
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .build/software/ympd/build.bash
  .build/software/ympd/container_build.bash
  .conf/dps_114/lighttpd.nextcloud.conf
  .github/workflows/amiberry.yml
  .github/workflows/armbian.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Release :champagne:

#6782 DietPi-Software | Ampache: Fix for Ampache v6 on Bullseye and Bookworm
  .github/workflows/dietpi-software.bash
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Bug :lady_beetle:, Via Forum, Docs change required, Upstream change

#6789 Meta | DietPi issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: META
