Repository MichaIng/DietPi, pull requests merged in 2023-08, with the labels that each got.

#6532 Orange Pi 5/ROCK 5B | Kernel update and migration
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .update/patches
  CHANGELOG.txt
Labels: Enhancement :dash:, ROCK 5B, Orange Pi 5, RK3588

#6533 Image | Add support for Orange Pi 5 Plus
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/func/dietpi-obtain_hw_model
Labels: Image Request :floppy_disk:, Docs change required

#6539 WiFi hotspot | Fix possibly failing DHCP server start
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6519 DietPi-Config -> WiFi-Hotspot: IP address was always changed to 192.168.42.1 in /etc/network/interfaces
  CHANGELOG.txt
  dietpi/dietpi-config
Labels: Enhancement :dash:

#6545 DietPi-Software | TasmoAdmin: Fix Nginx and Lighttpd config on Bookworm
  .conf/dps_27/lighttpd.tasmoadmin.3.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.3.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Bookworm, Upstream change

#6553 Update dietpi-globals
  dietpi/func/dietpi-globals
Labels: Spelling

#6556 DietPi-Installer | Fix ARMv7 image creations on ARMv8 hosts
  .build/images/dietpi-installer
  CHANGELOG.txt
Labels: Bug :lady_beetle:, Installer :diamond_shape_with_a_dot_inside:

#6551 WiFi Hotspot | General cleanup
  .update/patches
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6558 WiFi Hotspot | Add 802.11ac/WiFi 5 and 5 GHz support
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Enhancement :dash:, Feature Request :factory:

#6563 Beta v8.21.0
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .conf/dps_27/lighttpd.tasmoadmin.3.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.3.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/quartz64.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/shellcheck.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_swapfile
  rootfs/etc/sysctl.d/97-dietpi.conf
Labels: Beta :test_tube:

#6574 DietPi-Config | WiFi Hotspot: Do not allow to enter a <8 character key
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6575 WiFi Hotspot | Add 802.11ax/WiFi 6 support (Bookworm only)
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Feature Request :factory:, Bookworm

#6579 Beta v8.21.1
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6580 Release v8.21
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .conf/dps_27/lighttpd.tasmoadmin.3.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.3.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/quartz64.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/shellcheck.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_swapfile
  rootfs/etc/sysctl.d/97-dietpi.conf
Labels: Release :champagne:
