Repository MichaIng/DietPi, pull requests merged in 2023-05, with the labels that each got.

#6355 DietPi-Software | UrBackup: Fix for obtaining latest version
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Via Forum

#6356 DietPi-Software | SABnzbd: Fix startup on Buster and install on RISC-V
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Buster, Upstream change, RISC-V

#6328 DietPi-Software | TasmoAdmin: Fixe firmware restriction error
  .conf/dps_27/apache.tasmoadmin.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6362 CI | DietPi-Software: Stop SSH and Mono XSP4 services
  .github/workflows/dietpi-software.yml
Labels: Enhancement :dash:, CI

#6359 Beta v8.17.1
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .conf/dps_27/apache.tasmoadmin.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  .conf/dps_59/raspimjpeg.sh
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6364 DietPi-Software | MinIO: Use fixed web UI port and solve conflict with LMS
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Via Forum, Docs change required

#6350 DietPi-Software | Restic: is a fast and secure backup program
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:

#6366 Beta v8.17.2
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6361 Release v8.17
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .conf/dps_27/apache.tasmoadmin.conf
  .conf/dps_27/lighttpd.tasmoadmin.conf
  .conf/dps_27/nginx.tasmoadmin.conf
  .conf/dps_59/raspimjpeg.sh
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Release :champagne:

#6371 DietPi-Software | Domoticz: Fix failing tarball unpacking
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6380 DietPi-Software | Replace youtube-dl with yt-dlp
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6375 DietPi-DDNS | Update FreeDNS API URL
  CHANGELOG.txt
  dietpi/dietpi-ddns
Labels: Upstream change

#6384 Live patch 0 | Fix missing executable bit on Restic install
  .update/version
Labels: Live patch

#6386 Live patch 1 | Fix endless hang when disabling RPi HEVC decoder
  .update/version
Labels: Live patch

#6391 DietPi-Build | Add support for Sparky SBC
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
Labels: Testing/testers required :arrow_down_small:, Sparky SBC, CI

#6365 CI | DietPi-Software: Check services and ports automatically after software installs
  .github/workflows/dietpi-software.bash
Labels: Enhancement :dash:, CI

#6395 Beta v8.18.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/shairport-sync.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-ddns
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6398 CI | DietPi-Software: Airsonic test fix
  .github/workflows/dietpi-software.bash
Labels: Bug :lady_beetle:, CI

#6401 CI | Squeezelite: Update/align workflow and add RISC-V support
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .github/workflows/squeezelite.yml
Labels: Enhancement :dash:, CI, RISC-V
