Repository MichaIng/DietPi, pull requests merged in 2023-02, with the labels that each got.

#6120 Fix WordPress letter casing
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: META, Spelling

#6124 Keep overlay prefix in sync with armbian
  .build/images/dietpi-installer
Labels: Enhancement :dash:, Orange Pi 5

#6129 DietPi-Build | Enable F2FS support for GitHub Actions runners
  .build/images/dietpi-build
Labels: Feature Request :factory:

#6078 Beta v8.14.0
  .build/images/NanoPiM3/boot.cmd
  .build/images/U-Boot/boot.cmd
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .github/workflows/dietpi-build.yml
  .github/workflows/gogs.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-wifidb
  dietpi/func/run_ntpd
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#6131 DietPi-Build | Attempt to solve Btrfs image generation failure
  .build/images/dietpi-build
  .build/images/dietpi-imager
Labels: Feature Request :factory:

#6144 DietPi-Software | Matrix-Synapse
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6138 Beta v8.14.1
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .meta/dietpi-bookworm-upgrade
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-wifidb
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#6148 Support of RISC-V (StarFive VisionFive 2) - step 1
  .build/images/dietpi-installer
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
Labels: Installer :diamond_shape_with_a_dot_inside:, Hardware related :computer:, META, RISC-V

#6146 Beta v8.14.2
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
Labels: Beta :test_tube:

#6152 DietPi-Installer | Remove pre-v8.14 workarounds
  .build/images/dietpi-installer
Labels: Enhancement :dash:

#6139 Release v8.14
  .build/images/NanoPiM3/boot.cmd
  .build/images/U-Boot/boot.cmd
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/dps_93/apache.pihole.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/shellcheck.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-login
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  dietpi/func/run_ntpd
  rootfs/etc/bashrc.d/dietpi.bash
  rootfs/etc/systemd/system/dietpi-firstboot.service
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/dietpi-postboot.service
  rootfs/etc/systemd/system/dietpi-preboot.service
  rootfs/etc/systemd/system/dietpi-ramlog.service
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Release

#6161 CI | Add checks for trailing space and multiple newline characters
  .build/images/OdroidC1/boot.ini
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .conf/dps_119/cava.conf
  .conf/dpv/protonvpn.template
  .github/workflows/gogs.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-survey_report
  .update/patches
  CONTRIBUTING.md
  README.md
  dietpi/dietpi-drive_manager
  dietpi/func/dietpi-set_hardware
Labels: Coding :bookmark_tabs:, CI

#6162 Live patch 0 | Fix serial getty baudrate override
  .update/version
Labels: Live patch

#6167 CI | Add Quartz64 kernel and U-Boot build workflow
  .github/workflows/quartz64.yml
Labels: Enhancement :dash:, Kernel related :dna:, CI, Quartz64

#6179 CI | Quartz64: Build tuning
  .build/images/Quartz64/quartz64_defconfig
  .github/workflows/quartz64.yml
Labels: Enhancement :dash:, Quartz64

#6182 Live patch 1 | Python 3: Fix Python installs due to changes in pip
  .update/version
Labels: Live patch

#6183 fix AUTO_SETUP_HEADLESS warning in dietpi-config
  dietpi/dietpi-config
Labels: Bug :lady_beetle:

#6184 Live patch 2 | Fix Python software uninstalls due to changes in pip
  .update/version
Labels: Live patch
