Repository MichaIng/DietPi, pull requests merged in 2023-06, with the labels that each got.

#6405 DietPi-Software | Domoticz: Fix install due to missing new dependency
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Solution available :clinking_glasses:, Upstream change

#6397 Beta v8.18.1
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .conf/desktop/lxqt/lxqt-bookworm.7z
  .conf/desktop/lxqt/lxqt-stretch.7z
  .conf/dps_59/raspimjpeg.sh
  .github/workflows/dietpi-software.bash
  .github/workflows/squeezelite.yml
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6410 Quartz64 | Fix Rockchip DDR binary repo
  .github/workflows/quartz64.yml
Labels: Quartz64, Upstream change

#6411 Beta v8.18.2
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6412 CHANGELOG | Typo
  CHANGELOG.txt
Labels: META

#6413 CI | DietPi-Software: Some fixes
  .github/workflows/dietpi-software.bash
Labels: CI

#6406 Release v8.18
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .conf/desktop/lxqt/lxqt-bookworm.7z
  .conf/desktop/lxqt/lxqt-stretch.7z
  .conf/dps_59/raspimjpeg.sh
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-ddns
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Release :champagne:

#6420 DietPi-Software | Spotifyd: Fix installed version and dependencies
  .conf/dps_199/spotifyd.conf
  .github/workflows/dietpi-software.bash
  dietpi/dietpi-software
Labels: Upstream change

#6428 DietPi-Software | Mopidy: On Bullseye and above, migrate APT repo to (new) Bullseye suite
  .meta/dietpi-bookworm-upgrade
  .update/patches
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6424 General | Add Debian Trixie support
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  dietpi/func/dietpi-obtain_hw_model
Labels: Feature Request :factory:, Trixie

#6429 Live patch 0 | Fix Debian version detection on RISC-V
  .update/version
Labels: Live patch, RISC-V

#6427 DietPi-Software | Remove Spotify Connect Web and Firefox Sync Server
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Docs change required

#6442 NanoPi R5/R6 | Update kernel package
  .update/patches
Labels: Enhancement :dash:, NanoPi R5S/R5C, NanoPi R6S/R6C

#6443 DietPi-Sofware | MediaWiki: A collaboration and documentation platform
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#6438 Beta v8.19.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .conf/dps_199/spotifyd.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_software
Labels: Beta :test_tube:

#6447 DietPi-Config | Add Allwinner H3 analogue 3.5mm onboard audio
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
Labels: Feature Request :factory:, Allwinner H3

#6450 CI | ympd: Add build scripts and workflow
  .build/software/ympd/build.bash
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Bookworm
