Repository MichaIng/DietPi, pull requests merged in 2023-07, with the labels that each got.

#6454 Update CHANGELOG.txt
  CHANGELOG.txt
Labels: Coding :bookmark_tabs:, Spelling

#6445 Release v8.19
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .build/software/ympd/build.bash
  .conf/dps_199/spotifyd.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Release :champagne:

#6456 Live patch 0 | Fix Pi-hole, ownCloud, Nextcloud, Pydio and WikiMedia install if Lighttpd is selected as webserver
  .update/version
Labels: Live patch

#6462 Live patch 1 | Fix applying dietpi-letsencrypt certificate for Lighttpd
  .update/version
Labels: Live patch

#6474 DietPi-Software | PaperMC - update download URL for Geyser and Floodgate plugins
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Upstream change

#6459 DietPi-Software | WiFi Hotspot: Cleanup and enhance deps and settings
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6492 Raspberry Pi | Resolve FFmpeg package conflicts on Bookworm
  .build/images/dietpi-installer
  .meta/dietpi-bookworm-upgrade
  .update/pre-patches
  CHANGELOG.txt
Labels: Bug :lady_beetle:, RPi, Bookworm

#6495 Live patch 2 | Prevent conflicting FFmpeg 4.3 package installs from RPi APT repo
  .update/version
Labels: Live patch

#6481 Update dietpi-letsencrypt, since the upgrade to bookworm Lighttpd is now …
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Enhancement :dash:, Security :lock:, Bookworm, Trixie

#6491 DietPi-Software | apache2 / NextCloud / ownCloud / Pi-hole: Disable deprecated X-XSS-Protection header, Enable in NextCloud to avoid admin panel warning
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Security :lock:

#6493 DietPi-Sofware | Homebridge: Bringing HomeKit support where there is none
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:

#6496 Beta v8.20.0
  .build/images/dietpi-installer
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6507 Fix dietpi-logclear failing on files in sticky bit directories
  CHANGELOG.txt
  dietpi/func/dietpi-logclear
Labels: Bullseye, Upstream change

#6508 DietPi-Software | vaultwarden: Workaround for automount bug
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .update/patches
  CHANGELOG.txt
Labels: Workaround available :ok:, Upstream change

#6510 NanoPi R5S/R5C/6 series | Update kernel to v5.10.160
  .build/images/dietpi-build
  .update/patches
  CHANGELOG.txt
Labels: Enhancement :dash:, NanoPi R5S/R5C, NanoPi R6S/R6C

#6499 Beta v8.20.1
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
Labels: Beta :test_tube:

#6498 Release v8.20
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .conf/dps_114/apache.nextcloud.conf
  .conf/dps_47/lighttpd.owncloud.conf
  .conf/dps_47/nginx.owncloud.conf
  .conf/dps_93/lighttpd.pihole.conf
  .conf/dps_93/nginx.pihole.conf
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-letsencrypt
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-logclear
  dietpi/func/dietpi-set_hardware
Labels: Release :champagne:

#6513 DietPi-Update | Hotfix for FFmpeg "downgrade" on RPi Bookworm
  .update/patches
  .update/pre-patches
Labels: Bug :lady_beetle:, RPi, Bookworm

#6514 DietPi-Update | Hotfix for FFmpeg "downgrade" on RPi Bookworm
  .update/patches
  .update/pre-patches
Labels: Bug :lady_beetle:, RPi, Bookworm

#6516 Update CHANGELOG.txt: Wikimedia -> MediaWiki?
  CHANGELOG.txt
Labels: META

#6517 Update dietpi-letsencrypt, bug introduced with my last commit
  CHANGELOG.txt
  dietpi/dietpi-letsencrypt
Labels: Bug :lady_beetle:, Live patch request :wrench:, Regression

#6520 Fix dietpi-logclear fails when ARRAY_LOGFILE_TRUNCATE empty
  dietpi/func/dietpi-logclear
Labels: Visual :rose:

#6522 Live patch 0 | Fix DietPi-LetsEncrypt SSL config for Lighttpd
  .update/version
Labels: Live patch
