Repository MichaIng/DietPi, pull requests merged in 2023-10, with the labels that each got.

#6661 DietPi-Software | ADS-B Feeder: Harden uninstall and fix beta tags
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:

#6674 DietPi-DDNS | Add provider YDNS
  CHANGELOG.txt
  dietpi/dietpi-ddns
Labels: Feature Request :factory:

#6680 Sparky SBC | Ship with updated initramfs
  CHANGELOG.txt
Labels: Bug :lady_beetle:, Sparky SBC, Image update :floppy_disk:

#6686 Beta v8.23.0
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6691 Beta v8.23.1
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6696 Beta v8.23.2
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6653 ROCK 3A | Migrate from rk35xx edge to rockchip64 current kernel
  .build/images/dietpi-installer
Labels: Enhancement :dash:, Testing/testers required :arrow_down_small:, ROCK 3A

#6697 Beta v8.23.3
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/vaultwarden/container_build.bash
  .github/workflows/vaultwarden.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6698 VisionFive 2 | Automatically reboot on first boot if an overlay was applied
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:, VisionFive 2

#6693 Release v8.23
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/gmediarender.yml
  .github/workflows/gogs.yml
  .github/workflows/shairport-sync.yml
  .github/workflows/squeezelite.yml
  .github/workflows/vaultwarden.yml
  .github/workflows/ympd.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Regression

#6701 Live patch 0 | Fix Sonarr install
  .update/version
Labels: Live patch

#6709 CI | Apply workaround for skipped autologin in emulated Trixie/Sid containers
  .github/workflows/dietpi-software.bash
Labels: CI, Upstream change, Trixie
