Repository MichaIng/DietPi, pull requests merged in 2023-04, with the labels that each got.

#6273 Reworked GPU driver installations for x86 systems
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .meta/dietpi-bookworm-upgrade
  .update/patches
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-set_hardware
Labels: Enhancement :dash:

#6246 Dietpi-Software | microblog.pub
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#6258 Beta v8.16.0
  .build/images/NanoPiM3/boot.cmd
  .build/images/OdroidC1/boot.ini
  .build/images/OdroidXU4/boot.ini
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/gogs.yml
  .github/workflows/quartz64.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/postboot
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6283 ROCK 3A | Generate images with a single ext4 partition
  .build/images/dietpi-build
Labels: Enhancement :dash:, ROCK 3A

#6288 DietPi-Config | Display Brightness Changes
  CHANGELOG.txt
  dietpi/dietpi-config
Labels: Enhancement :dash:

#6285 Beta v8.16.1
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/vaultwarden.yml
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-wifidb
Labels: Beta :test_tube:

#6294 Beta v8.16.2
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6282 Release v8.16
  .build/images/NanoPiM3/boot.cmd
  .build/images/OdroidC1/boot.ini
  .build/images/OdroidXU4/boot.ini
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/build.bash
  .build/software/gogs/container_build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/amiberry.yml
  .github/workflows/gogs.yml
  .github/workflows/quartz64.yml
  .github/workflows/vaultwarden.yml
  .meta/dietpi-bookworm-upgrade
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-cpuinfo
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-set_swapfile
  dietpi/func/dietpi-wifidb
  dietpi/postboot
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Release :champagne:

#6308 DietPi-Software | Home Assistant/HTPC Manager: Add pkg-config for cryptography source builds
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Via Forum, Upstream change

#6311 Live patch 0 | Unmask cron service which was accidentially shipped mask with recent images
  .update/version
Labels: Live patch

#6318 CI | DietPi-Software: Further fixes and workarounds
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  dietpi/dietpi-software
Labels: CI

#6325 DietPi-Software | Fix Rust installs on RPi 4 with 32-bit image
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: External Bug :lady_beetle:, RPi4

#6301 DietPi-Config | Audio: Intel + firmware-sof-signed
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
Labels: Enhancement :dash:

#6314 DietPi-Banner | add letsencrypt certificate details
  CHANGELOG.txt
  dietpi/func/dietpi-banner
Labels: Feature Request :factory:

#6331 NanoPi R series | Update Ethernet LED udev rules
  .build/images/dietpi-installer
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  dietpi/func/dietpi-obtain_hw_model
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:, ROCK 4, NanoPi R4S, NanoPi R5S/R5C, NanoPi R2S, NanoPi R6S/R6C

#6336 CI | DietPi-Software: Add target branch and owner inputs
  .github/workflows/dietpi-software.yml
Labels: Enhancement :dash:, CI

#6341 CI | DietPi-Software: Add an option to fake an RPi system on ARM
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  dietpi/dietpi-update
Labels: Enhancement :dash:, CI

#6334 DietPi-Software | Add openHAB to software catalogue
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software Request :cd:, Docs change required

#6323 Raspberry Pi | Fix analogue onboard audio selection
  .update/patches
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Via Forum, RPi, Upstream change

#6303 DietPi-Software | Moonlight: Game streaming client for Sunshine and NVIDIA GameStream
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:, Testing/testers required :arrow_down_small:, RPi, Docs change required

#6339 DietPi-Software | Moonlight Qt : GUI game streaming client for Sunshine and NVIDIA GameStream
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Software Request :cd:

#6343 Beta v8.17.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/gmediarender/container_build.bash
  .build/software/gogs/container_build.bash
  .build/software/shairport-sync/container_build.bash
  .build/software/squeezelite/container_build.bash
  .build/software/vaultwarden/build.bash
  .build/software/vaultwarden/container_build.bash
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  README.md
  dietpi/dietpi-config
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/dietpi-update
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  rootfs/etc/cron.daily/dietpi
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6353 DietPi-Software | openHAB: Disable plain HTTP change change HTTPS port
  dietpi/dietpi-software
Labels: Enhancement :dash:
