Repository MichaIng/DietPi, pull requests merged in 2024-05, with the labels that each got.

#7053 CI | Armbian: Set Git user and email to repo owner name and email
  .github/workflows/armbian.yml
Labels: Bug :lady_beetle:, CI

#7042 Orange Pi 3 LTS/Radxa ZERO 3 | Add support
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Image Request :floppy_disk:

#7056 DietPi-Software | X-Server
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:

#6995 Image | Add support for Orange Pi Zero 2W
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .meta/dietpi-survey_report
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Image Request :floppy_disk:, Orange Pi Zero 2W

#7059 DietPi-WiFiDB | Minor coding
  dietpi/func/dietpi-wifidb
Labels: Coding :bookmark_tabs:

#7061 DietPi-Pre-patches | Typo
  .update/pre-patches
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#7064 Orange Pi Zero 3 | Fix lost Ethernet on reboot on 1.5 GB RAM variant
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  .update/patches
  CHANGELOG.txt
Labels: External Bug :lady_beetle:, Orange Pi Zero 3

#7067 Odroid XU4 | Update boot.ini for Linux 6.1/6.6
  .build/images/OdroidXU4/boot.ini
  .build/images/dietpi-installer
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Enhancement :dash:, Odroid XU4

#7062 Beta v9.4.1
  .build/images/OdroidXU4/boot.ini
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/armbian.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Beta :test_tube:

#7068 Beta v9.4.2
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#7063 Release v9.4
  .build/images/OdroidXU4/boot.ini
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/armbian.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/raspberrypi-sys-mods.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-cloudshell
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/dietpi-vpn
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  dietpi/func/dietpi-wifidb
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Release :champagne:

#7075 Init v9.5
  .meta/dietpi-survey_report
  .update/version
  dietpi/func/dietpi-globals
Labels: META

#7082 Fix shairport-sync-airplay2 install
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Via Forum, Regression
