Repository MichaIng/DietPi, pull requests merged in 2024-04, with the labels that each got.

#7008 DietPi-Software | SABnzbd: Skip obsolete dependencies
  dietpi/dietpi-software
Labels: Enhancement :dash:

#7003 Beta v9.3.0
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .build/software/ympd/build.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Beta :test_tube:

#7017 CHANGELOG | Add v9.3 PR link
  CHANGELOG.txt
Labels: META

#7016 Release v9.3
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/gmediarender/build.bash
  .build/software/raspberrypi-sys-mods/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .build/software/ympd/build.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi.txt
  dietpi/dietpi-config
  dietpi/dietpi-login
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
Labels: Release :champagne:

#7021 Init v9.4
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#7033 DietPi-Imager | Fix GPT backup partition table handling
  .build/images/dietpi-imager
  CHANGELOG.txt
Labels: Bug :lady_beetle:, Installer :diamond_shape_with_a_dot_inside:

#7050 CI | Armbian: Fix rebase syntax and remove obsolete workarounds
  .github/workflows/armbian.yml
Labels: Bug :lady_beetle:, CI
