Repository MichaIng/DietPi, pull requests merged in 2024-03, with the labels that each got.

#6952 CI | Squeezelite: Use again latest commit
  .build/software/squeezelite/build.bash
  dietpi/dietpi-config
  dietpi/dietpi-software
Labels: Enhancement :dash:, CI

#6953 Beta v9.2.0
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/dietpi-software-build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/desktop/lxqt/lxqt-buster.7z
  .conf/desktop/lxqt/lxqt-trixie.7z
  .conf/dps_114/nginx.nextcloud.conf
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#6940 changed instructions to switch branch
  BRANCH_SYSTEM.md
Labels: META

#6844 dietpi-banner: Adds support for displaying ram usage
  CHANGELOG.txt
  dietpi/func/dietpi-banner
Labels: Enhancement :dash:

#6957 Beta v9.2.1
  .update/patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#6965 DietPi-Patches | Fix Amiberry update text
  .update/patches
Labels: META

#6955 Release v9.2
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/dietpi-software-build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/desktop/lxqt/lxqt-buster.7z
  .conf/desktop/lxqt/lxqt-trixie.7z
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  BRANCH_SYSTEM.md
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Release :champagne:

#6972 Init v9.3
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#6988 install stage0: log to firstrunsetup
  dietpi/dietpi-login
Labels: Enhancement :dash:
