Repository MichaIng/DietPi, pull requests merged in 2024-12, with the labels that each got.

#7292 DietPi-Software | frp
  .github/workflows/dietpi-software.bash
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Bug :lady_beetle:, Docs change required, Upstream change

#7309 DietPi-DDNS | Allow to update IPv4 as well as IPv6
  CHANGELOG.txt
  dietpi/dietpi-ddns
Labels: Feature request :factory:

#7307 DietPi-Software | Sonarr: Migrate to v4
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Upstream change

#7310 Beta v9.0.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .conf/dps_96/conf
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/quartz64.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#7314 Beta v9.9.0 appendix
  .build/images/dietpi-installer
  CHANGELOG.txt
Labels: Beta :test_tube:

#7316 CHANGELOG | Update new image changelogs
  CHANGELOG.txt
Labels: Beta :test_tube:

#7313 Release v9.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/shairport-sync/build.bash
  .build/software/squeezelite/build.bash
  .conf/dps_96/conf
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/quartz64.yml
  .meta/dietpi-survey_report
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-config
  dietpi/dietpi-ddns
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-obtain_hw_model
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Release :champagne:

#7317 CHANGELOG.txt: Release date corrected
  CHANGELOG.txt
Labels: Docs change required, Release :champagne:

#7319 Init v9.10
  .meta/dietpi-survey_report
  .update/version
  CHANGELOG.txt
  dietpi/func/dietpi-globals
Labels: META

#7322 Live patch 0 | Fix Sonarr v4 permissions for updater
  .update/version
Labels: Live patch

#7328 Live patches for Fail2Ban Dropbear filter
  .update/version
Labels: Live patch

#7332 Dietpi-Software | Raspotify
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Upstream change
