Repository MichaIng/DietPi, pull requests merged in 2024-07, with the labels that each got.

#7124 dietpi-{software,services}: Added soju IRC bouncer
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software request :cd:, Docs change required

#7111 Beta v9.6.0
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  rootfs/etc/systemd/system/ifup@.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
Labels: Beta :test_tube:

#6880 Add a separate function inside dietpi-globals to generate troubleshoot template for the forum
  dietpi/func/dietpi-globals
Labels: Enhancement :dash:

#7137 Beta v9.6.1
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
Labels: Beta :test_tube:

#7143 DietPi-Installer | Remove pre-v9.6 steps
  .build/images/dietpi-installer
Labels: Installer :diamond_shape_with_a_dot_inside:

#7142 Release v9.6
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/Amiberry/build.bash
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-backup
  dietpi/dietpi-config
  dietpi/dietpi-drive_manager
  dietpi/dietpi-services
  dietpi/dietpi-software
  dietpi/func/dietpi-banner
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_software
  rootfs/etc/systemd/system/ifup@.service
  rootfs/etc/systemd/system/ifup@.service.d/dietpi.conf
Labels: Release :champagne:

#7144 CHANGELOG | Add v9.6 release PR URL
  CHANGELOG.txt
Labels: Beta :test_tube:

#7145 CHANGELOG | Add v9.6 release PR URL
  CHANGELOG.txt
Labels: Release :champagne:

#7149 DietPi-Software | Box86/Box64: Fix directory removal on install
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Regression

#7153 DietPi-Software | Node.js: Install libatomic1 only where required
  dietpi/dietpi-software
Labels: Enhancement :dash:

#7166 DietPi-Software | correct a typo
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:
