Repository MichaIng/DietPi, pull requests merged in 2024-02, with the labels that each got.

#6892 DietPi-Build/Installer | Add support for RPi with new kernel/firmware
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Feature Request :factory:, RPi, Installer :diamond_shape_with_a_dot_inside:, RPi 5

#6904 DietPi-Software | vaultwarden: Fix builds on 32-bit ARM via "release-micro" profile
  .build/software/vaultwarden/build.bash
Labels: Bug :lady_beetle:, ARMv6, ARMv7, CI, Upstream change

#6913 Beta v9.1.0
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/gmediarender/build.bash
  .build/software/vaultwarden/build.bash
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_48/apache.pydio.conf
  .github/workflows/amiberry.yml
  .github/workflows/armbian.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-rpi-firmware-migration
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Beta :test_tube:

#6918 Updated pgrep condition to exclude script process
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-sync
Labels: Enhancement :dash:

#6902 Nano Pi R5S/R5C and 6 series | Move to Armbian kernel and bootloader builds
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .github/workflows/dietpi-build.yml
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Enhancement :dash:, NanoPi R5S/R5C, NanoPi 6 series

#6920 Beta v9.1.1
  .build/images/dietpi-build
  .build/images/dietpi-installer
  .build/software/squeezelite/build.bash
  .github/workflows/dietpi-build.yml
  .meta/dietpi-rpi-firmware-migration
  .update/patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
Labels: Beta :test_tube:

#6921 Release v9.1
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/gmediarender/build.bash
  .build/software/squeezelite/build.bash
  .build/software/vaultwarden/build.bash
  .conf/dps_114/nginx.nextcloud.conf
  .conf/dps_48/apache.pydio.conf
  .github/workflows/amiberry.yml
  .github/workflows/armbian.yml
  .github/workflows/dietpi-build.yml
  .github/workflows/dietpi-software-build.yml
  .github/workflows/dietpi-software.bash
  .github/workflows/dietpi-software.yml
  .github/workflows/quartz64.yml
  .github/workflows/raspberrypi-sys-mods.yml
  .github/workflows/shellcheck.yml
  .meta/dietpi-rpi-firmware-migration
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  dietpi/dietpi-backup
  dietpi/dietpi-drive_manager
  dietpi/dietpi-software
  dietpi/dietpi-sync
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
  dietpi/func/dietpi-set_software
  rootfs/var/lib/dietpi/services/dietpi-firstboot.bash
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Release :champagne:

#6923 DietPi-Installer | Fix for changed gcc-base version on Trixie
  .build/images/dietpi-installer
Labels: Beta :test_tube:

#6924 DietPi-Installer | Fix for changed gcc-base version on Trixie
  .build/images/dietpi-installer
Labels: Release :champagne:

#6933 Live patch 0 | Fix Nextcloud Nginx config, serving wrong MIME types
  .conf/dps_114/nginx.nextcloud.conf
  .update/version
Labels: Via Forum, Live patch

#6931 Fixed: Cannot build pip dependency 'webrtc-noise-gain' required for HA's integrations
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Upstream change
