Repository MichaIng/DietPi, pull requests merged in 2025-01, with the labels that each got.

#7335 DietPi-Software | Home Assistant: Work around incompatible dependencies on ARMv6 and RISC-V
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: ARMv6, External bug :lady_beetle:, RISC-V

#7342 DietPi-Software | Cuberite: Run in new detached foreground mod
  .github/workflows/dietpi-software.bash
  dietpi/dietpi-software
Labels: Enhancement :dash:

#7347 DietPi-Software | myMPD: Enable for Bookworm on ARMv6
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, ARMv6, Bookworm

#7348 RISC-V | Switch to Debian Trixie
  .build/images/dietpi-build
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/dietpi-software.bash
  .update/patches
  .update/pre-patches
  CHANGELOG.txt
  dietpi/dietpi-software
  dietpi/func/dietpi-set_software
Labels: Enhancement :dash:, RISC-V

#7352 DietPi-Software | PaperMC: Fix Geyser plugin version for older PaperMC versions
  .build/images/dietpi-build
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/dietpi-software.bash
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Bug :lady_beetle:, Bullseye, Bookworm, Upstream change

#7351 Removed software "Network Tools"
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Docs change required

#7355 Live patch 3 | Fix Sonarr v4 permissions for updater for installed Sonarr v4 instances
  .update/version
Labels: Live patch

#7356 CI | Apply better workaround for failing services on QEMU-emulated Trixie containers
  .build/images/dietpi-build
  .build/software/Amiberry/container_build.bash
  .build/software/dietpi-software-build.bash
  .build/software/vaultwarden/build.bash
  .github/workflows/dietpi-software.bash
Labels: Enhancement :dash:, CI

#7354 DietPi-Software | Removal of file managers and text editors
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  dietpi/dietpi-software
Labels: Enhancement :dash:, Docs change required
