Repository MichaIng/DietPi, pull requests merged in 2025-09, with the labels that each got.

#7732 DietPi-Software | ProFTPD: Remove deprecated setting
  .conf/dps_94/conf
  .update/patches
Labels: Upstream change

#7729 fs_partition_resize: create ext3/ext4 journal and fix F2FS expansion
  .build/images/Quartz64/quartz64_defconfig
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .github/workflows/quartz64.yml
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  dietpi/dietpi-login
  rootfs/etc/systemd/system/dietpi-fs_partition_resize.service
  rootfs/etc/systemd/system/ifupdown-pre.service.d/dietpi.conf
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Bug :lady_beetle:, Enhancement :dash:

#7742 dietpi-config: typo
  dietpi/dietpi-config
Labels: Bug :lady_beetle:

#7747 DietPi-Software | Add LazyLibrarian
  dietpi/dietpi-services
  dietpi/dietpi-software
Labels: Software request :cd:

#7755 Added xen hv drive support
  CHANGELOG.txt
  dietpi/dietpi-drive_manager
  rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Labels: Enhancement :dash:
