Repository MichaIng/DietPi, pull requests merged in 2025-03, with the labels that each got.

#7458 dietpi-software: Spotifyd: add missing dependencies
  .update/pre-patches
  dietpi/dietpi-software
Labels: Upstream change

#7461 fix(patches): fix a typo when updating RPi firmware
  .update/patches
Labels: Spelling

#7462 fix DietPi-Set_hardware > lcdpanel (waveshare32)
  CHANGELOG.txt
  dietpi/func/dietpi-set_hardware
Labels: Bug :lady_beetle:, Raspberry Pi
