Repository MichaIng/DietPi, pull requests merged in 2025-04, with the labels that each got.

#7452 add fish to System
  .meta/dietpi-survey_report
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Feature request :factory:, Docs change required

#7479 Beta 9.12.0
  .build/images/dietpi-build
  .build/images/dietpi-imager
  .build/images/dietpi-installer
  .build/software/squeezelite/build.bash
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  .update/pre-patches
  .update/version
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
  dietpi/func/dietpi-globals
  dietpi/func/dietpi-set_hardware
Labels: Beta :test_tube:

#7484 Fix typo in Folding@Home description on dietpi-software
  dietpi/dietpi-software
Labels: Spelling

#7474 Use editor configured by update-alternatives
  CHANGELOG.txt
  dietpi/dietpi-autostart
  dietpi/dietpi-backup
  dietpi/dietpi-cleaner
  dietpi/dietpi-explorer
  dietpi/dietpi-services
  dietpi/dietpi-vpn
Labels: Enhancement :dash:

#7492 ci: Amiberry: Implement Amiberry v7 and Amiberry-Lite
  .build/software/Amiberry/container_build.bash
  .build/software/amiberry-lite/build.bash
  .build/software/amiberry/build.bash
  .build/software/dietpi-software-build.bash
  .github/workflows/amiberry.yml
  .github/workflows/dietpi-software-build.yml
  .github/workflows/dietpi-software.bash
  .meta/dietpi-survey_report
  .update/patches
  CHANGELOG.txt
  README.md
  dietpi/dietpi-software
Labels: Enhancement :dash:, Software request :cd:

#7494 dietpi-backup: fix SSHFS support
  dietpi/dietpi-backup
Labels: Bug :lady_beetle:

#7495 dietpi-software: WiringPi: complement Orange Pi 5 Ultra/CM5/4A support
  dietpi/dietpi-software
Labels: Enhancement :dash:

#7505 ci: dietpi-build: use new ARM runners where applicable
  .build/images/dietpi-build
  .github/workflows/dietpi-build.yml
Labels: Enhancement :dash:, CI
